/* Shared BOBS roadmap UI. Read-only, lazy Google reads; no progress ledger or business writes. */
(function(){'use strict';
if(window.BOBS_ROADMAP||window.self!==window.top)return;
const base=new URL('.',location.href),K=window.BOBS_ROADMAP_CORE;let open=false,busy=false,queued=false,active='',draftDirty=false,epoch=0,loadedIds=new Set(),records=new Map(),common=null,tools=null,endpoint='',lastFocus;
const markers={done:'✅',pending:'○',review:'⚠️',unknown:'?',na:'—'},stateNames={done:'Completed and verified',pending:'Pending',review:'Review needed',unknown:'Not verified',na:'Not applicable / optional'};
function el(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x}
function frames(){const frame=document.getElementById('methodFrame');return frame?.getAttribute('src')?[new URL(frame.getAttribute('src'),base).href]:[]}
function context(){const x=K.context(location.href,base.href,frames());const selection=document.getElementById('outletId');if(selection?.value)x.outlet=selection.value;return x}
function activity(x){const names={'index.html':'BOBS home','outlets.html':'Outlet setup','outlet-method-flow.html':'Outlet method analysis','method2-item.html':'Item quantities, sides and packing','recipe-cost-editor.html':'Recipe reference and production requirement','purchase-cost-editor.html':'Purchase costs','idli-staffing.html':'Workforce coverage','reverse-thp.html':'Salary and full-cost planning','fixed-expenses.html':'Outlet expenses'};let name=x.item;if(!name&&x.cat&&x.index!==''&&tools)name=tools.catalogue[x.cat]?.[Number(x.index)]?.name||'';return [x.outlet?'Outlet '+x.outlet:'Company overview',/method1/.test(x.page)?'Method1':/method2|recipe-cost|purchase-cost|idli|reverse-thp/.test(x.page)?'Method2':'',name,names[x.page]||x.page.replace('.html','').replaceAll('-',' ')].filter(Boolean).join(' → ')}
async function script(file,ready){if(ready())return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=new URL(file,base);s.onload=resolve;s.onerror=()=>reject(Error('Could not load '+file));document.head.append(s)});if(!ready())throw Error(file+' did not initialise')}
async function dependencies(){if(tools)return tools;await script('shared_data.js',()=>!!window.ITEM_DATA);await script('method2-core.js',()=>!!window.M2);await script('bobs-cost-flow.js',()=>!!window.BOBS_COST_FLOW);await script('idli-support-core.js',()=>!!window.IdliSupport);tools={M2:window.M2,C:window.BOBS_COST_FLOW,S:window.IdliSupport,catalogue:window.ITEM_DATA};return tools}
async function vault(){if(endpoint)return endpoint;endpoint=window.BOBS_CONFIG?.DATA_VAULT_WEB_APP_URL||'';if(!endpoint){const r=await fetch(new URL('bobs-config.js',base));if(!r.ok)throw Error('Could not read central Google configuration');const text=await r.text();endpoint=text.match(/DATA_VAULT_WEB_APP_URL:\s*'([^']+)'/)?.[1]||''}if(!endpoint)throw Error('Google Data Vault is not configured');return endpoint}
async function jsonp(params){await vault();return new Promise((resolve,reject)=>{const callback='bobsRoadmapRead_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script');let done=false;const cleanup=()=>{clearTimeout(timer);s.remove();if(done==='late'){window[callback]=()=>{};setTimeout(()=>delete window[callback],60000)}else delete window[callback]},finish=(error,value)=>{if(done)return;done=true;cleanup();error?reject(error):resolve(value)};const timer=setTimeout(()=>{if(done)return;done='late';cleanup();reject(Error('Google progress read timed out'))},15000);window[callback]=data=>finish(null,data);s.onerror=()=>finish(Error('Google progress read failed'));s.src=endpoint+'?'+new URLSearchParams({...params,callback,_bobs:Date.now()});document.head.append(s)})}
async function record(outlet,module,key='default'){const r=await jsonp({action:'moduleGet',outletId:outlet,module,recordKey:key});if(r?.ok!==true)throw Error(r?.error||module+' was not verified');let value=r.data??r.record?.data;if(typeof value==='string')value=JSON.parse(value);if(value&&typeof value==='object')return value;if(r.found===false)return null;throw Error(module+' presence was not confirmed')}
async function result(fn){try{return {status:'ok',value:await fn()}}catch(e){return {status:'error',error:e.message}}}
async function outlets(){const r=await jsonp({action:'outletList'});if(r?.ok!==true||!Array.isArray(r.outlets))throw Error('Saved outlet list not verified');return r.outlets.filter(x=>String(x.status||'ACTIVE').toUpperCase()!=='DELETED').map(x=>{const d=x.data||x;return {id:String(x.outletId||d.id||x.id||''),name:String(x.outletName||d.name||x.name||'Outlet')}}).filter(x=>x.id)}
async function recipes(){const m=await record('COMPANY','BOBS_STANDARD_RECIPE','ACTIVE_V1');if(!m)return [];if(m.schema!=='BOBS_RECIPE_KNOWLEDGE_MANIFEST_V1'||!Array.isArray(m.chunkKeys)||!m.chunkKeys.length)throw Error('Standard recipe manifest incomplete');const parts=await Promise.all(m.chunkKeys.map(k=>record('COMPANY','BOBS_STANDARD_RECIPE',k)));const all=[];for(let i=0;i<parts.length;i++){const p=parts[i];if(!p||p.schema!=='BOBS_RECIPE_KNOWLEDGE_CHUNK_V1'||String(p.token)!==String(m.token)||Number(p.index)!==i||Number(p.total)!==parts.length||!Array.isArray(p.records))throw Error('Standard recipe chunk failed verification');all.push(...p.records)}if(all.length!==Number(m.recordCount))throw Error('Standard recipe count mismatch');return all}
async function readCommon(){await dependencies();const [outs,refs,staff,allocation]=await Promise.all([result(outlets),result(recipes),result(()=>record('COMPANY','STAFF_MASTER')),result(()=>record('COMPANY','HR_OUTLET_ALLOCATION'))]);return {outlets:outs,recipes:refs,staff,allocation}}
async function readOutlet(id){const pairs=await Promise.all([['method1','METHOD1'],['method2','METHOD2'],['equipment','EQUIPMENT_PLAN'],['workload','WORKLOAD_PLAN'],['workforce','WORKFORCE_PLAN'],['expenses','FIXED_EXPENSES']].map(async([key,module])=>[key,await result(()=>record(id,module))]));return Object.fromEntries(pairs)}
function link(href,text){const a=el('a',text);const url=new URL(href,base);if(url.origin!==base.origin||!url.pathname.startsWith(base.pathname))return el('span',text);a.href=url.href;a.target='_blank';a.rel='opener';a.addEventListener('click',()=>{url.searchParams.set('returnTo',location.href);a.href=url.href});return a}
const toggle=el('button','☰ BOBS progress');toggle.id='bobsRoadmapToggle';toggle.type='button';toggle.setAttribute('aria-controls','bobsRoadmap');toggle.setAttribute('aria-expanded','false');const panel=el('aside');panel.id='bobsRoadmap';panel.hidden=true;panel.tabIndex=-1;panel.setAttribute('aria-label','Entire BOBS project roadmap');const backdrop=el('div');backdrop.id='bobsRoadmapBackdrop';backdrop.hidden=true;backdrop.setAttribute('aria-hidden','true');
const head=el('div',undefined,'roadmap-top'),title=el('h2','BOBS roadmap'),close=el('button','Close ×');close.type='button';close.setAttribute('aria-label','Close BOBS roadmap');head.append(title,close);const intro=el('p','Entire project → outlets → methods → items. Saved progress is shared; opening a page does not earn a tick.');const locationBox=el('p',undefined,'roadmap-context');locationBox.id='bobsRoadmapLocation';const dirtyNote=el('p','This page has unsaved edits. Ticks below describe the saved version.','roadmap-reason');dirtyNote.hidden=true;const trail=el('p',undefined,'roadmap-reason');const legend=el('p','✅ Completed · 🔵 You are here · ○ Pending · ⚠️ Review needed · ? Not verified · — Optional / not applicable','roadmap-legend');const status=el('p','Open the roadmap to read saved progress.');status.id='bobsRoadmapStatus';status.setAttribute('role','status');const refresh=el('button','Refresh progress');refresh.type='button';const choose=el('div',undefined,'roadmap-outlets');const content=el('div');content.id='bobsRoadmapContent';const help=el('details'),helpTitle=el('summary','How progress works');help.className='roadmap-help';help.append(helpTitle,intro,trail,legend);const scope=el('details'),scopeTitle=el('summary','Outlets / company overview');scope.id='bobsRoadmapScope';scope.append(scopeTitle,choose);panel.append(head,locationBox,dirtyNote,refresh,status,scope,help,content);
function layout(){const dock=innerWidth>=1100;document.body.classList.toggle('bobs-roadmap-docked',open&&dock);document.body.classList.toggle('bobs-roadmap-overlay',open&&!dock);backdrop.hidden=!open||dock;if(open&&!dock){panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true')}else{panel.removeAttribute('role');panel.removeAttribute('aria-modal')}}
function show(){open=true;lastFocus=document.activeElement;panel.hidden=false;toggle.setAttribute('aria-expanded','true');layout();updateContext();close.focus();if(!common)refreshAll();else render()}
function hide(){open=false;panel.hidden=true;toggle.setAttribute('aria-expanded','false');layout();(lastFocus?.isConnected?lastFocus:toggle).focus()}
function updateContext(){const ctx=context();locationBox.textContent='🔵 You are here: '+activity(ctx);dirtyNote.hidden=!draftDirty;trail.textContent=ctx.chain.length>1?'Opening route: '+ctx.chain.map(x=>x.replace('.html','').replaceAll('-',' ')).join(' → '):'Earlier and later stages are shown below. This is the project roadmap, not browser visit history.'}
function stageRow(step,depth=0){const li=el('li');li.dataset.state=step.status;li.dataset.step=step.id;const ctx=context(),current=K.currentStep(ctx.page);if(depth===0&&Number(step.id)===current&&(active===ctx.outlet||!ctx.outlet)){li.setAttribute('aria-current','step')}const label=markers[step.status]+' '+(depth===0?step.id+'. ':'')+step.title;const heading=el('details');if(heading){const summary=el('summary',label);summary.className='roadmap-title';summary.setAttribute('aria-label',step.title+': '+stateNames[step.status]);heading.append(summary);if(li.hasAttribute('aria-current')){heading.open=true;summary.append(el('span',' — 🔵 You are here'))}heading.append(el('p',step.reason,'roadmap-reason'));heading.append(link(step.href,'Open '+step.title+' ↗'));const list=el('ol',undefined,'roadmap-substeps');step.children.forEach(x=>list.append(stageRow(x,depth+1)));heading.append(list);li.append(heading)}else{const title=el('div',label,'roadmap-title');title.setAttribute('aria-label',step.title+': '+stateNames[step.status]);li.append(title,el('p',step.reason,'roadmap-reason'),link(step.href,'Open ↗'))}return li}
function projection(id){return K.evaluate({outlet:id,outlets:common.outlets,recipes:common.recipes,records:{...records.get(id),staff:common.staff,allocation:common.allocation}},tools)}
function render(){if(open&&(content.contains(document.activeElement)||choose.contains(document.activeElement)))close.focus();updateContext();choose.replaceChildren();const outs=common?.outlets?.value||[],ctx=context();const ids=[...new Set(outs.map(x=>x.id).concat(ctx.outlet?[ctx.outlet]:[]))];for(const id of ids){const name=outs.find(x=>x.id===id)?.name||'Outlet '+id,b=el('button',name+' ('+id+')'+(records.has(id)?' — '+projection(id).completed+' verified stages':' — Progress not loaded yet'));b.type='button';b.setAttribute('aria-pressed',String(active===id));b.onclick=()=>select(id);choose.append(b)}const company=el('button','Company overview');company.type='button';company.setAttribute('aria-pressed',String(active===''));company.onclick=()=>{active='';scope.open=false;close.focus();render()};choose.append(company);const all=el('button','Check all outlets');all.type='button';all.id='bobsRoadmapAll';all.disabled=busy;all.onclick=()=>{outs.forEach(x=>loadedIds.add(x.id));refreshAll()};choose.append(all);content.replaceChildren();if(!active){content.append(el('h3','Company-wide roadmap'));const count=outs.length;content.append(el('p',common?.outlets.status==='error'?'? '+common.outlets.error:count?'✅ '+count+' saved outlets verified':'○ Save outlet setup first'));content.append(link('outlets.html','Open company/outlet setup ↗'));content.append(el('p','Choose an outlet above to expand its ten stages and selected items. Click an outlet or Check all outlets to load its saved progress.'));const list=el('ol');K.labels.forEach((name,i)=>{let state='pending',reason='Expand each outlet to inspect saved requirements';if(i===0)state=common?.outlets.status==='error'?'unknown':count?'done':'pending';else if(count&&outs.every(x=>records.has(x.id))){const steps=outs.map(x=>projection(x.id).stages[i]);state=K.aggregate(steps);reason='Across '+count+' saved outlets'}list.append(stageRow(K.node(String(i+1),name,state,reason,['outlets.html','recipe-master.html','outlet-method-flow.html','method2.html','workload-planner.html','staff.html','fixed-expenses.html','method2.html','cogs-outlet-analysis.html','breakeven-overall.html'][i]))) });content.append(list);return}if(!records.has(active)){content.append(el('p','Reading saved records for Outlet '+active+'…'));return}const view=projection(active);content.append(el('h3','Outlet '+active+' — '+view.completed+' / '+view.total+' verified stages'));const next=el('p',view.next?'Next required: '+view.next.title+' — '+view.next.reason:'All recorded requirements complete','roadmap-context');content.append(next);if(view.next)content.append(link(view.next.href,'Go to next required step ↗'));const list=el('ol');view.stages.forEach(x=>list.append(stageRow(x)));content.append(list);content.append(el('p','Reports without a saved review-completion record stay pending. Equipment records without menu fingerprints require review. No completion is assumed.','roadmap-reason'))}
async function select(id){active=id;loadedIds.add(id);scope.open=false;close.focus();render();if(!records.has(id))await refreshAll()}
async function refreshAll(){if(busy){queued=true;return}busy=true;const request=++epoch;refresh.disabled=true;status.textContent='Checking saved Google records…';try{const next=await readCommon();if(request!==epoch)return;common=next;const ctx=context();if(!active&&ctx.outlet&&loadedIds.size===0){active=ctx.outlet;loadedIds.add(active)}for(const id of loadedIds){const row=await readOutlet(id);if(request!==epoch)return;records.set(id,row)}render();status.textContent='Saved progress checked '+new Date().toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata'})+'. Business date '+tools.C.today()+'.'}catch(e){status.textContent='Progress not verified — '+e.message;content.replaceChildren(el('p','Retry progress reads. The page and your edits remain available.'))}finally{busy=false;refresh.disabled=false;const all=document.getElementById('bobsRoadmapAll');if(all)all.disabled=false;if(queued){queued=false;refreshAll()}}}
function boot(){const space=el('div');space.id='bobsRoadmapSpace';space.setAttribute('aria-hidden','true');document.body.prepend(space);document.body.append(toggle,backdrop,panel);toggle.onclick=()=>open?hide():show();close.onclick=hide;backdrop.onclick=hide;refresh.onclick=refreshAll;window.addEventListener('resize',layout);document.addEventListener('keydown',e=>{if(!open)return;if(e.key==='Escape'){e.preventDefault();hide()}if(e.key==='Tab'&&innerWidth<1100){if(!panel.contains(document.activeElement)){e.preventDefault();close.focus();return}const list=[...panel.querySelectorAll('button,a,summary')].filter(x=>{if(!x.getClientRects().length||x.disabled)return false;for(let parent=x.parentElement;parent&&parent!==panel;parent=parent.parentElement)if(parent.tagName==='DETAILS'&&!parent.open&&!parent.querySelector(':scope > summary')?.contains(x))return false;return true});if(!list.length)return;const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});for(const type of ['input','change'])document.addEventListener(type,e=>{if(!panel.contains(e.target)&&e.target.matches('input,select,textarea')){draftDirty=true;if(open)updateContext()}});let timer;const schedule=()=>{if(open){clearTimeout(timer);timer=setTimeout(refreshAll,400)}};window.addEventListener('focus',schedule);window.addEventListener('message',e=>{if(e.origin===location.origin&&/^bobs-.+-saved$/.test(e.data?.type||''))schedule()});if(window.BroadcastChannel)for(const name of ['bobs-method2','bobs-recipe-master','bobs-full-cost','bobs-workload-plan']){const ch=new BroadcastChannel(name);ch.onmessage=e=>{if(/^bobs-.+-saved$/.test(e.data?.type||''))schedule()}}window.BOBS_ROADMAP={open:show,close:hide,refresh:refreshAll,context,getState:()=>({active,busy,loaded:[...loadedIds]})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
