/* BOBS GOOGLE SHEETS DATA VAULT
 * 111Q: permanent vault records are read/recovered non-destructively.
 */
const VAULT_SPREADSHEET_ID='19E32HO9npGZugzpzVm4UvxA40A001GRDVRsBtHy-FR8';
const VAULT_SHEET='BOBS_SNAPSHOT_VAULT';
const INDEX_SHEET='VAULT_INDEX';
function doPost(e){try{const b=JSON.parse((e&&e.postData&&e.postData.contents)||'{}');if(b.action==='snapshot')return json_(saveSnapshot_(b));if(b.action==='list'||b.action==='snapshotList')return json_(listSnapshots_());if(b.action==='restore')return json_(restoreSnapshot_(b.snapshotId));if(b.action==='outletList')return json_(listOutletRecords_());return json_({ok:false,error:'Unknown action'});}catch(err){return json_({ok:false,error:String(err)});}}
function doGet(e){try{const a=String((e&&e.parameter&&e.parameter.action)||'').trim();let out;if(a==='outletList')out=listOutletRecords_();else if(a==='snapshotList'||a==='list')out=listSnapshots_();else if(a==='restore')out=restoreSnapshot_(e.parameter.snapshotId);else out={ok:true,service:'BOBS Google Sheets Data Vault',readActions:['outletList','snapshotList','restore']};return json_(out,e&&e.parameter&&e.parameter.callback);}catch(err){return json_({ok:false,error:String(err)},e&&e.parameter&&e.parameter.callback);}}
function json_(o,cb){const s=JSON.stringify(o);if(cb&&/^[A-Za-z_$][\w$]*$/.test(cb))return ContentService.createTextOutput(cb+'('+s+');').setMimeType(ContentService.MimeType.JAVASCRIPT);return ContentService.createTextOutput(s).setMimeType(ContentService.MimeType.JSON);}
function vault_(){return SpreadsheetApp.openById(VAULT_SPREADSHEET_ID);}
function ensure_(){const ss=vault_();let v=ss.getSheetByName(VAULT_SHEET);if(!v){v=ss.insertSheet(VAULT_SHEET);v.appendRow(['snapshotId','createdAt','reason','payload']);}let i=ss.getSheetByName(INDEX_SHEET);if(!i){i=ss.insertSheet(INDEX_SHEET);i.appendRow(['snapshotId','createdAt','reason','status']);}return{ss,v,i};}
function saveSnapshot_(b){const x=ensure_(),id=b.snapshotId||('GS-SNAP-'+Date.now());x.v.appendRow([id,new Date().toISOString(),b.reason||'BOBS protected snapshot',JSON.stringify(b.data||{})]);x.i.appendRow([id,new Date().toISOString(),b.reason||'','PROTECTED']);return{ok:true,snapshotId:id};}
function listSnapshots_(){const x=ensure_(),vals=x.i.getDataRange().getValues();return{ok:true,snapshots:vals.slice(1).map(r=>({snapshotId:r[0],createdAt:r[1],reason:r[2],status:r[3]}))};}
function restoreSnapshot_(id){const x=ensure_(),vals=x.v.getDataRange().getValues();for(let n=1;n<vals.length;n++){if(String(vals[n][0])===String(id))return{ok:true,snapshotId:id,data:JSON.parse(vals[n][3])};}return{ok:false,error:'Snapshot not found'};}
function listOutletRecords_(){const x=ensure_(),vals=x.v.getDataRange().getValues();for(let n=vals.length-1;n>=1;n--){let p;try{p=JSON.parse(vals[n][3]||'{}');}catch(e){continue;}const c=[p['bobs-permanent-outlet-master'],p['outlets-master'],p.outlets,p.outletMaster];for(const v of c){if(Array.isArray(v)&&v.length)return{ok:true,source:'DATA_VAULT',snapshotId:vals[n][0],createdAt:vals[n][1],outlets:v};if(v&&Array.isArray(v.outlets)&&v.outlets.length)return{ok:true,source:'DATA_VAULT',snapshotId:vals[n][0],createdAt:vals[n][1],outlets:v.outlets};}}return{ok:true,source:'DATA_VAULT',outlets:[]};}
