/* BOBS Method 2 — unified pricing layer. Industry price is preserved; Current Selling Price is separate/editable. */
(function(){
'use strict';
const KEY='method2-item-state';
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function state(){try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');s.qtys=s.qtys||{};s.prod=s.prod||{};s.condiments=s.condiments||{};s.packaging=s.packaging||{};s.pricing=s.pricing||{};s.commercial=s.commercial||{};return s}catch(e){return{qtys:{},prod:{},condiments:{},packaging:{},pricing:{},commercial:{}}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function pkey(cat,i){return String(cat)+'::'+String(i)}
function unitCost(r){if(!r)return 0;for(const k of ['unitCost','costPerUnit','perUnitCost','productionCost']){const v=num(r[k]);if(v>0)return v}const batch=num(r.batchCost||r.totalCost),y=num(r.standardYield||r.yieldQty||r.yield);return y>0&&batch>0?batch/y:0}
function findRecipe(name){const n=norm(name),a=window.BOBS_METHOD2_RM_RECIPES||[];return a.find(r=>norm(r.name)===n)||a.find(r=>norm(r.name).includes(n)||n.includes(norm(r.name)))||null}
function condimentCost(cat,i){const s=state(),a=Array.isArray(s.condiments[pkey(cat,i)])?s.condiments[pkey(cat,i)]:[];return a.reduce((z,x)=>z+unitCost(findRecipe(x.recipeName||x.name))*num(x.qty),0)}
function packagingCost(cat,i){if(typeof window.BOBS_METHOD2_PACKAGING_COST==='function')return num(window.BOBS_METHOD2_PACKAGING_COST(cat,i));const a=state().packaging[pkey(cat,i)]||[];return Array.isArray(a)?a.reduce((z,x)=>z+num(x.qty)*num(x.unitCost),0):0}
function spoilage(cat,i){const el=document.querySelector('.spoilInput[data-cat="'+CSS.escape(cat)+'"][data-i="'+i+'"]');return el?num(el.value):0}
function pricing(cat,i,item){const s=state(),k=pkey(cat,i),o=s.pricing[k]||{};const industry=Number.isFinite(Number(item.__industryStandardPrice))?num(item.__industryStandardPrice):num(item.price);const current=o.currentPrice==null||o.currentPrice===''?industry:num(o.currentPrice);return{markupPct:o.markupPct==null?25:num(o.markupPct),industryStandardPrice:industry,currentPrice:current}}
function currentPrice(cat,i,item){const p=pricing(cat,i,item);return p.currentPrice>0?p.currentPrice:p.industryStandardPrice}
window.BOBS_METHOD2_CURRENT_PRICE=currentPrice
function cogs(cat,i,item){const sel=document.querySelector('.modeSelect[data-cat="'+CSS.escape(cat)+'"][data-i="'+i+'"]');if(sel&&sel.value==='production'){const food=unitCost(findRecipe(item.name))*(1+spoilage(cat,i)/100)+condimentCost(cat,i)*(1+spoilage(cat,i)/100);return food+packagingCost(cat,i)}return num(item.purchasedCost)+packagingCost(cat,i)}
function style(){if(document.getElementById('m2PricingStyle'))return;const s=document.createElement('style');s.id='m2PricingStyle';s.textContent='.m2-price-grid{display:none!important}';document.head.appendChild(s)}
function render(cat,i){const item=ITEM_DATA[cat]&&ITEM_DATA[cat][i],sel=document.querySelector('.modeSelect[data-cat="'+CSS.escape(cat)+'"][data-i="'+i+'"]');if(!item||!item.eligible||!sel)return;if(!Number.isFinite(Number(item.__industryStandardPrice)))item.__industryStandardPrice=num(item.price);syncPrice(cat,i);style()}
function syncPrice(cat,i){const item=ITEM_DATA[cat][i];if(!item)return;if(!Number.isFinite(Number(item.__industryStandardPrice)))item.__industryStandardPrice=num(item.price);const p=pricing(cat,i,item);if(p.currentPrice>0)item.price=p.currentPrice}
function augmentSyncPayload(){const original=window.fetch;if(window.__m2PriceFetchWrapped||typeof original!=='function')return;window.fetch=function(input,init){try{const body=init&&init.body;if(typeof body==='string'&&body.indexOf('"method":"method2"')!==-1){const payload=JSON.parse(body);if(Array.isArray(payload.rows)){payload.rows=payload.rows.map(r=>{const cat=r.category,i=(ITEM_DATA[r.category]||[]).findIndex(x=>x.name===r.item),item=i>=0?ITEM_DATA[r.category][i]:null;if(item){if(!Number.isFinite(Number(item.__industryStandardPrice)))item.__industryStandardPrice=num(item.price);const p=pricing(r.category,i,item);r.industryStandardSellingPrice=p.industryStandardPrice;r.currentSellingPrice=p.currentPrice;r.markupPct=p.markupPct}return r});init=Object.assign({},init,{body:JSON.stringify(payload)})}}}catch(e){}return original.call(this,input,init)};window.__m2PriceFetchWrapped=true}
function trigger(){try{if(typeof window.recalc==='function')window.recalc()}catch(e){}try{if(typeof window.BOBS_METHOD2_RM_RECALC==='function')window.BOBS_METHOD2_RM_RECALC()}catch(e){}try{if(typeof window.BOBS_METHOD2_FINAL_RECALC==='function')window.BOBS_METHOD2_FINAL_RECALC()}catch(e){}}
function all(){if(!window.ITEM_DATA||!window.CAT_ORDER)return;style();CAT_ORDER.forEach(cat=>ITEM_DATA[cat].forEach((item,i)=>{if(item.eligible){syncPrice(cat,i);render(cat,i)}}));augmentSyncPayload();trigger()}
function loadLayer(src){const s=document.createElement('script');s.src=src;s.defer=true;document.head.appendChild(s)}
function boot(){loadLayer('method2-packaging.js?v=2026-09-13-2');loadLayer('method2-final-cogs.js?v=2026-09-13-2');loadLayer('method2-cogs-breakdown.js?v=2026-09-13-2');loadLayer('method2-unified-loader.js?v=2026-09-13-4');loadLayer('method2-analysis-panel.js?v=2026-09-13-2');setTimeout(all,0);document.addEventListener('change',e=>{if(e.target.matches&&e.target.matches('.modeSelect,.spoilInput'))setTimeout(all,20)});document.addEventListener('bobs-method2-condiment-change',()=>setTimeout(all,20));document.addEventListener('bobs-method2-packaging-change',()=>setTimeout(all,20));let tries=0;const poll=setInterval(()=>{tries++;if((window.BOBS_METHOD2_RM_RECIPES||[]).length&&window.BOBS_METHOD2_PACKAGING_COST&&window.BOBS_METHOD2_FINAL_RECALC){all();clearInterval(poll)}else if(tries>=20)clearInterval(poll)},500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
