/* BOBS Method 2 — unified pricing layer. Industry price is preserved; Current Selling Price is separate/editable. */
(function(){
'use strict';
const KEY='method2-item-state';
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function state(){try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');s.qtys=s.qtys||{};s.prod=s.prod||{};s.condiments=s.condiments||{};s.packaging=s.packaging||{};s.pricing=s.pricing||{};s.commercial=s.commercial||{};return s}catch(e){return{qtys:{},prod:{},condiments:{},packaging:{},pricing:{},commercial:{}}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function pkey(cat,i){return String(cat)+'::'+String(i)}
function unitCost(r){if(!r)return 0;for(const k of ['unitCost','costPerUnit','perUnitCost','productionCost']){const v=num(r[k]);if(v>0)return v}const batch=num(r.batchCost||r.totalCost),y=num(r.standardYield||r.yieldQty||r.yield);return y>0&&batch>0?batch/y:0}
function findRecipe(name){const n=norm(name),a=window.BOBS_METHOD2_RM_RECIPES||[];return a.find(r=>norm(r.name)===n)||a.find(r=>norm(r.name).includes(n)||n.includes(norm(r.name)))||null}
function condimentCost(cat,i){const s=state(),a=Array.isArray(s.condiments[pkey(cat,i)])?s.condiments[pkey(cat,i)]:[];return a.reduce((z,x)=>z+unitCost(findRecipe(x.recipeName||x.name))*num(x.qty),0)}
function packagingCost(cat,i){if(typeof window.BOBS_METHOD2_PACKAGING_COST==='function')return num(window.BOBS_METHOD2_PACKAGING_COST(cat,i));const a=state().packaging[pkey(cat,i)]||[];return Array.isArray(a)?a.reduce((z,x)=>z+num(x.qty)*num(x.unitCost),0):0}
function commercial(cat,i){const c=state().commercial[pkey(cat,i)]||{};return Object.assign({purchasePrice:'',packQty:'',salesConversion:'1',safetyPct:5},c)}
function actualPurchaseCogs(cat,i,item){const c=commercial(cat,i);let base=num(item.purchasedCost);if(c.purchasePrice!==''&&num(c.packQty)>0)base=num(c.purchasePrice)/num(c.packQty)/Math.max(num(c.salesConversion)||1,1);return base+packagingCost(cat,i)}
function rawProductionCogs(item,cat,i){return unitCost(findRecipe(item.name))+condimentCost(cat,i)}
function spoilage(cat,i){const el=document.querySelector('.spoilInput[data-cat="'+CSS.escape(cat)+'"][data-i="'+i+'"]');return el?num(el.value):0}
function pricing(cat,i,item){const s=state(),k=pkey(cat,i),o=s.pricing[k]||{};const industry=Number.isFinite(Number(item.__industryStandardPrice))?num(item.__industryStandardPrice):num(item.price);const current=o.currentPrice==null||o.currentPrice===''?industry:num(o.currentPrice);return{markupPct:o.markupPct==null?25:num(o.markupPct),industryStandardPrice:industry,currentPrice:current}}
function currentPrice(cat,i,item){const p=pricing(cat,i,item);return p.currentPrice>0?p.currentPrice:p.industryStandardPrice}
window.BOBS_METHOD2_CURRENT_PRICE=currentPrice
function cogs(cat,i,item){const sel=document.querySelector('.modeSelect[data-cat="'+CSS.escape(cat)+'"][data-i="'+i+'"]');if(sel&&sel.value==='production'){const food=rawProductionCogs(item,cat,i)*(1+spoilage(cat,i)/100);return food+packagingCost(cat,i)}return actualPurchaseCogs(cat,i,item)}
function style(){if(document.getElementById('m2PricingStyle'))return;const s=document.createElement('style');s.id='m2PricingStyle';s.textContent='.m2-price-grid{display:grid;grid-template-columns:1.1fr .8fr 1fr 1fr 1fr;gap:7px;margin:6px 8px 10px;padding:9px;background:var(--paper-dark,#f3f3f3);border-radius:9px;border:1px solid #ddd}.m2-price-head{font-size:9px;color:var(--ink-soft);font-weight:700}.m2-price-val{font-size:12px;font-weight:700}.m2-price-input{width:100%;box-sizing:border-box;padding:5px 6px;border:1px solid #bbb;border-radius:5px;font-size:12px;background:#fff}.m2-industry{font-size:12px;font-weight:800}.m2-price-note{grid-column:1/-1;font-size:9.5px;color:var(--ink-soft)}@media(max-width:850px){.m2-price-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.m2-price-grid{grid-template-columns:1fr 1fr}.m2-price-note{grid-column:1/-1}}';document.head.appendChild(s)}
function render(cat,i){const item=ITEM_DATA[cat]&&ITEM_DATA[cat][i],sel=document.querySelector('.modeSelect[data-cat="'+CSS.escape(cat)+'"][data-i="'+i+'"]');if(!item||!item.eligible||!sel)return;const row=sel.closest('.item-row');if(!row)return;if(!Number.isFinite(Number(item.__industryStandardPrice)))item.__industryStandardPrice=num(item.price);let box=row.nextElementSibling;if(!box||!box.classList.contains('m2-price-grid')){box=document.createElement('div');box.className='m2-price-grid';row.insertAdjacentElement('afterend',box)}box.style.display='grid';const old=pricing(cat,i,item),cc=cogs(cat,i,item),preferred=cc*(1+old.markupPct/100),mode=sel.value==='production'?'Production':'Purchase';box.innerHTML='<div><div class="m2-price-head">OVERALL COGS — '+mode.toUpperCase()+'</div><div class="m2-price-val">₹'+(cc>0?cc.toFixed(2):'—')+'</div><div style="font-size:9px;color:#666">'+(sel.value==='production'?'Recipe + Condiments + Food Spoilage + Packing':'Purchase Cost + Packing')+'</div></div><div><div class="m2-price-head">MARK UP %</div><input class="m2-price-input m2-markup" type="number" min="0" step="0.1" value="'+old.markupPct+'"></div><div><div class="m2-price-head">SELLING PRICE BASED ON MARKUP</div><div class="m2-price-val">₹'+(cc>0?preferred.toFixed(2):'—')+'</div></div><div><div class="m2-price-head">INDUSTRY STANDARD SELLING PRICE</div><div class="m2-industry">₹'+old.industryStandardPrice.toFixed(2)+'</div><div style="font-size:8.5px;color:#666">Reference only — not changed by outlet edits</div></div><div><div class="m2-price-head">CURRENT SELLING PRICE</div><input class="m2-price-input m2-current-price" type="number" min="0" step="0.01" value="'+old.currentPrice+'"></div><div class="m2-price-note">Industry Standard Selling Price is the existing Method 2 benchmark and is preserved. Current Selling Price starts from that benchmark, but is stored separately and can be edited without changing the benchmark. Markup price is calculated from Actual Overall COGS; UUWP/Protected COGS remains a separate assessment layer.</div>';
box.querySelector('.m2-markup').addEventListener('input',e=>{const s=state(),k=pkey(cat,i),v=num(e.target.value),cur=pricing(cat,i,item).currentPrice;s.pricing[k]=Object.assign({},s.pricing[k]||{},{markupPct:v,currentPrice:cur});save(s);render(cat,i);trigger()});
box.querySelector('.m2-current-price').addEventListener('input',e=>{const s=state(),k=pkey(cat,i),v=num(e.target.value),p=pricing(cat,i,item);s.pricing[k]=Object.assign({},s.pricing[k]||{},{markupPct:p.markupPct,currentPrice:v,industryStandardPrice:p.industryStandardPrice});save(s);item.price=v;render(cat,i);trigger()})}
function syncPrice(cat,i){const item=ITEM_DATA[cat][i];if(!item)return;if(!Number.isFinite(Number(item.__industryStandardPrice)))item.__industryStandardPrice=num(item.price);const p=pricing(cat,i,item);if(p.currentPrice>0)item.price=p.currentPrice}
function augmentSyncPayload(){const original=window.fetch;if(window.__m2PriceFetchWrapped||typeof original!=='function')return;window.fetch=function(input,init){try{const body=init&&init.body;if(typeof body==='string'&&body.indexOf('"method":"method2"')!==-1){const payload=JSON.parse(body);if(Array.isArray(payload.rows)){payload.rows=payload.rows.map(r=>{const cat=r.category,i=(ITEM_DATA[r.category]||[]).findIndex(x=>x.name===r.item),item=i>=0?ITEM_DATA[r.category][i]:null;if(item){if(!Number.isFinite(Number(item.__industryStandardPrice)))item.__industryStandardPrice=num(item.price);const p=pricing(r.category,i,item);r.industryStandardPrice=p.industryStandardPrice;r.currentSellingPrice=p.currentPrice;r.markupPct=p.markupPct}return r});init=Object.assign({},init,{body:JSON.stringify(payload)})}}}catch(e){}return original.call(this,input,init)};window.__m2PriceFetchWrapped=true}
function trigger(){try{if(typeof window.recalc==='function')window.recalc()}catch(e){}try{if(typeof window.BOBS_METHOD2_RM_RECALC==='function')window.BOBS_METHOD2_RM_RECALC()}catch(e){}try{if(typeof window.BOBS_METHOD2_FINAL_RECALC==='function')window.BOBS_METHOD2_FINAL_RECALC()}catch(e){}}
function all(){if(!window.ITEM_DATA||!window.CAT_ORDER)return;style();CAT_ORDER.forEach(cat=>ITEM_DATA[cat].forEach((item,i)=>{if(item.eligible){syncPrice(cat,i);render(cat,i)}}));augmentSyncPayload();trigger()}
function loadLayer(src){const s=document.createElement('script');s.src=src;s.defer=true;document.head.appendChild(s)}
function boot(){loadLayer('method2-packaging.js?v=2026-09-13-2');loadLayer('method2-final-cogs.js?v=2026-09-13-2');loadLayer('method2-cogs-breakdown.js?v=2026-09-13-1');loadLayer('method2-unified-loader.js?v=2026-09-13-2');setTimeout(all,0);document.addEventListener('change',e=>{if(e.target.matches&&e.target.matches('.modeSelect,.spoilInput'))setTimeout(all,20)});document.addEventListener('bobs-method2-condiment-change',()=>setTimeout(all,20));document.addEventListener('bobs-method2-packaging-change',()=>setTimeout(all,20));let tries=0;const poll=setInterval(()=>{tries++;if((window.BOBS_METHOD2_RM_RECIPES||[]).length&&window.BOBS_METHOD2_PACKAGING_COST&&window.BOBS_METHOD2_FINAL_RECALC){all();clearInterval(poll)}else if(tries>=20)clearInterval(poll)},500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();