/* BOBS Method 2 — production pricing layer. Existing state is preserved; pricing is additive. */
(function(){
'use strict';
const KEY='method2-item-state';
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function state(){try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');s.qtys=s.qtys||{};s.prod=s.prod||{};s.condiments=s.condiments||{};s.packaging=s.packaging||{};s.pricing=s.pricing||{};return s}catch(e){return{qtys:{},prod:{},condiments:{},packaging:{},pricing:{}}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function pkey(cat,i){return String(cat)+'::'+String(i)}
function unitCost(r){if(!r)return 0;for(const k of ['unitCost','costPerUnit','perUnitCost','productionCost']){const v=num(r[k]);if(v>0)return v}const batch=num(r.batchCost||r.totalCost),y=num(r.standardYield||r.yieldQty||r.yield);return y>0&&batch>0?batch/y:0}
function findRecipe(name){const n=norm(name),a=window.BOBS_METHOD2_RM_RECIPES||[];return a.find(r=>norm(r.name)===n)||a.find(r=>norm(r.name).includes(n)||n.includes(norm(r.name)))||null}
function condimentCost(cat,i){const s=state(),a=Array.isArray(s.condiments[pkey(cat,i)])?s.condiments[pkey(cat,i)]:[];return a.reduce((z,x)=>{const r=findRecipe(x.recipeName||x.name),uc=unitCost(r),q=num(x.qty);return z+(uc>0&&q>0?uc*q:0)},0)}
function packagingCost(cat,i){if(typeof window.BOBS_METHOD2_PACKAGING_COST==='function')return num(window.BOBS_METHOD2_PACKAGING_COST(cat,i));const a=state().packaging[pkey(cat,i)]||[];return a.reduce((z,x)=>z+num(x.qty)*num(x.unitCost),0)}
function rawCogs(item,cat,i){return unitCost(findRecipe(item.name))+condimentCost(cat,i)}
function spoilage(cat,i){const el=document.querySelector('.spoilInput[data-cat="'+CSS.escape(cat)+'"][data-i="'+i+'"]');return el?num(el.value):0}
function finalCogs(item,cat,i){const food=rawCogs(item,cat,i)*(1+spoilage(cat,i)/100),pack=packagingCost(cat,i);return food+pack}
function ps(cat,i,item){const s=state(),k=pkey(cat,i),o=s.pricing[k]||{};return{markupPct:o.markupPct==null?25:num(o.markupPct),currentPrice:o.currentPrice==null||o.currentPrice===''?num(item.price):num(o.currentPrice)}}
function style(){if(document.getElementById('m2PricingStyle'))return;const s=document.createElement('style');s.id='m2PricingStyle';s.textContent='.m2-price-grid{display:grid;grid-template-columns:1.15fr .7fr 1fr 1fr;gap:7px;margin:6px 8px 10px;padding:9px;background:var(--paper-dark,#f3f3f3);border-radius:9px;border:1px solid #ddd}.m2-price-head{font-size:9.5px;color:var(--ink-soft);font-weight:700}.m2-price-val{font-size:12px;font-weight:700}.m2-price-input{width:100%;box-sizing:border-box;padding:5px 6px;border:1px solid #bbb;border-radius:5px;font-size:12px;background:#fff}.m2-price-note{grid-column:1/-1;font-size:9.5px;color:var(--ink-soft)}@media(max-width:700px){.m2-price-grid{grid-template-columns:1fr 1fr}.m2-price-note{grid-column:1/-1}}';document.head.appendChild(s)}
function render(cat,i){const item=ITEM_DATA[cat][i],sel=document.querySelector('.modeSelect[data-cat="'+CSS.escape(cat)+'"][data-i="'+i+'"]');if(!item||!item.eligible||!sel)return;const row=sel.closest('.item-row');if(!row)return;let box=row.nextElementSibling;if(!box||!box.classList.contains('m2-price-grid')){box=document.createElement('div');box.className='m2-price-grid';row.insertAdjacentElement('afterend',box)}if(sel.value!=='production'){box.style.display='none';return}box.style.display='grid';const old=ps(cat,i,item),food=rawCogs(item,cat,i)*(1+spoilage(cat,i)/100),pack=packagingCost(cat,i),cc=food+pack,preferred=cc*(1+old.markupPct/100);box.innerHTML='<div><div class="m2-price-head">COGS OF SALES ITEM</div><div class="m2-price-val">₹'+(cc>0?cc.toFixed(2):'—')+'</div><div style="font-size:9px;color:#666">Food after spoilage ₹'+(food>0?food.toFixed(2):'—')+' + Parcel/Serving ₹'+pack.toFixed(2)+'</div></div><div><div class="m2-price-head">MARK UP %</div><input class="m2-price-input m2-markup" type="number" min="0" step="0.1" value="'+old.markupPct+'"></div><div><div class="m2-price-head">SELLING PRICE BASED ON MARKUP</div><div class="m2-price-val">₹'+(cc>0?preferred.toFixed(2):'—')+'</div></div><div><div class="m2-price-head">CURRENT SELLING PRICE</div><input class="m2-price-input m2-current-price" type="number" min="0" step="0.01" value="'+old.currentPrice+'"></div><div class="m2-price-note">Final COGS = <b>Recipe Master item + selected condiments + food spoilage + selected parcel/packaging/serving items</b>. Packaging and serving costs are added after food spoilage; markup is applied after all costs. Current Selling Price drives sales and profit.</div>';
box.querySelector('.m2-markup').addEventListener('input',e=>{const s=state(),k=pkey(cat,i),v=num(e.target.value);s.pricing[k]=Object.assign({},s.pricing[k]||{},{markupPct:v,currentPrice:old.currentPrice});save(s);render(cat,i);trigger()});
box.querySelector('.m2-current-price').addEventListener('input',e=>{const s=state(),k=pkey(cat,i),v=num(e.target.value);s.pricing[k]=Object.assign({},s.pricing[k]||{},{markupPct:old.markupPct,currentPrice:v});save(s);syncPrice(cat,i);render(cat,i);trigger()})}
function syncPrice(cat,i){const item=ITEM_DATA[cat][i],v=ps(cat,i,item).currentPrice;if(v>0)item.price=v}
function trigger(){try{if(typeof window.recalc==='function')window.recalc()}catch(e){}try{if(typeof window.BOBS_METHOD2_RM_RECALC==='function')window.BOBS_METHOD2_RM_RECALC()}catch(e){}try{if(typeof window.BOBS_METHOD2_FINAL_RECALC==='function')window.BOBS_METHOD2_FINAL_RECALC()}catch(e){}}
function all(){if(!window.ITEM_DATA||!window.CAT_ORDER)return;style();CAT_ORDER.forEach(cat=>ITEM_DATA[cat].forEach((item,i)=>{if(item.eligible){syncPrice(cat,i);render(cat,i)}}));trigger()}
function loadLayer(src){const s=document.createElement('script');s.src=src;s.defer=true;s.onload=()=>setTimeout(all,60);document.head.appendChild(s)}
function boot(){loadLayer('method2-packaging.js?v=2026-09-13-2');loadLayer('method2-final-cogs.js?v=2026-09-13-1');setTimeout(all,0);document.addEventListener('change',e=>{if(e.target.matches&&e.target.matches('.modeSelect,.spoilInput'))setTimeout(all,20)});document.addEventListener('bobs-method2-condiment-change',()=>setTimeout(all,20));document.addEventListener('bobs-method2-packaging-change',()=>setTimeout(all,20));let tries=0;const poll=setInterval(()=>{tries++;if((window.BOBS_METHOD2_RM_RECIPES||[]).length&&window.BOBS_METHOD2_PACKAGING_COST&&window.BOBS_METHOD2_FINAL_RECALC){all();clearInterval(poll)}else if(tries>=20)clearInterval(poll)},500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
