/* BOBS Method 2 — Recipe Master costing engine. Production COGS = item Recipe Master COGS + selected condiment COGS. */
(function(){
'use strict';
const VAULT='https://script.google.com/macros/s/AKfycbwmvTLGxFQ2KQvzP9tr1Ry5LOi8EWRcfP6YxtOKiLUCLJqDpQ8Nsk12zThc1Yj4A9Pf4A/exec';
const RM={outletId:'COMPANY',module:'RECIPE_MASTER',recordKey:'STANDARD_V1'};
let recipes=[];
function jsonp(url){return new Promise((resolve,reject)=>{const cb='m2Cost_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script');let done=false,t=setTimeout(()=>finish(false,new Error('Recipe Master timeout')),9000);function finish(ok,v){if(done)return;done=true;clearTimeout(t);try{delete window[cb]}catch(e){}s.remove();ok?resolve(v):reject(v)}window[cb]=d=>finish(true,d);s.onerror=()=>finish(false,new Error('Recipe Master read failed'));s.src=url+'&callback='+cb+'&_bobs='+Date.now();document.head.appendChild(s)})}
function parse(q){let d=q&&q.data!=null?q.data:null;if(typeof d==='string'){try{d=JSON.parse(d)}catch(e){}}if(d&&d.data&&typeof d.data==='object')d=d.data;return(d&&Array.isArray(d.recipes)?d.recipes:null)||(q&&Array.isArray(q.recipes)?q.recipes:null)||(q&&q.record&&q.record.data&&Array.isArray(q.record.data.recipes)?q.record.data.recipes:null)||(q&&q.record&&Array.isArray(q.record.recipes)?q.record.recipes:null)}
function norm(s){return String(s||'').toLowerCase().replace(/idly/g,'idli').replace(/[^a-z0-9]+/g,' ').trim()}
function recipeFor(name){const n=norm(name);return recipes.find(r=>norm(r.name)===n)||recipes.find(r=>norm(r.name).includes(n)||n.includes(norm(r.name)))||null}
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}
function unitCost(r){if(!r)return 0;for(const k of ['unitCost','costPerUnit','perUnitCost','productionCost']){const v=num(r[k]);if(v>0)return v}const batch=num(r.batchCost||r.totalCost)||((r.ingredients||[]).reduce((total,x)=>total+num(x&&x[1])*num(x&&x[3]),0)),y=num(r.standardYield||r.yield||r.standardYieldQty||r.yieldQty);return batch>0&&y>0?batch/y:0}
function state(){try{const s=JSON.parse(localStorage.getItem('method2-item-state')||'{}');s.condiments=s.condiments||{};return s}catch(e){return{qtys:{},prod:{},condiments:{}}}}
function key(cat,i){return String(cat)+'::'+String(i)}
function selectedCondimentCost(cat,i){const s=state(),a=Array.isArray(s.condiments[key(cat,i)])?s.condiments[key(cat,i)]:[];return a.reduce((sum,x)=>{const r=recipeFor(x.recipeName||x.name),uc=unitCost(r),q=num(x.qty);return sum+(uc>0&&q>0?uc*q:0)},0)}
function itemBaseCost(item){return unitCost(recipeFor(item.name))}
function isProduction(cat,i){const item=ITEM_DATA[cat][i];if(!item||!item.eligible)return false;const s=document.querySelector('.modeSelect[data-cat="'+CSS.escape(cat)+'"][data-i="'+i+'"]');return !!s&&s.value==='production'}
function getCost(cat,i){const item=ITEM_DATA[cat][i];return itemBaseCost(item)+selectedCondimentCost(cat,i)}
function refresh(){let grandRev=0,grandCost=0;CAT_ORDER.forEach(cat=>{const k=cat.replace(/\s+/g,'_');let units=0,rev=0;ITEM_DATA[cat].forEach((item,i)=>{const inp=document.querySelector('.qtyInput[data-cat="'+CSS.escape(cat)+'"][data-i="'+i+'"]');if(!inp)return;const qty=num(inp.value),pricing=inp.dataset.unit==='g'?qty/1000:qty,r=pricing*num(item.price);units+=qty;rev+=r;if(qty>0){let cost=item.purchasedCost;if(isProduction(cat,i)){const spoil=num((document.querySelector('.spoilInput[data-cat="'+CSS.escape(cat)+'"][data-i="'+i+'"]')||{}).value);const perUnit=getCost(cat,i);cost=perUnit>0?perUnit*(1+spoil/100):0}grandCost+=cost*qty}const cell=document.getElementById('irev-'+k+'-'+i);if(cell)cell.textContent=qty>0?'₹'+Math.round(r).toLocaleString('en-IN'):''});const sub=document.getElementById('sub-'+k);if(sub)sub.textContent=Math.round(units).toLocaleString('en-IN')+' units · ₹'+Math.round(rev).toLocaleString('en-IN');grandRev+=rev});window.currentTotal=grandRev;const a=document.getElementById('grandTotalSale'),b=document.getElementById('grandTotalCost'),c=document.getElementById('grandTotalProfit');if(a)a.textContent='₹'+Math.round(grandRev).toLocaleString('en-IN');if(b)b.textContent='₹'+Math.round(grandCost).toLocaleString('en-IN');if(c)c.textContent='₹'+Math.round(grandRev-grandCost).toLocaleString('en-IN')}
function showChain(cat,i){const item=ITEM_DATA[cat][i];if(!item||!isProduction(cat,i))return;const k=cat.replace(/\s+/g,'_'),d=document.getElementById('costChain-'+k+'-'+i);if(!d)return;const base=itemBaseCost(item),cond=selectedCondimentCost(cat,i),spoil=num((document.querySelector('.spoilInput[data-cat="'+CSS.escape(cat)+'"][data-i="'+i+'"]')||{}).value);if(base<=0&&cond<=0){d.innerHTML='<div class="ccRow"><span>Recipe Master COGS</span><span>Not available</span></div>';return}const final=(base+cond)*(1+spoil/100);d.innerHTML='<div class="ccRow"><span>Recipe Master — '+item.name+'</span><span>₹'+base.toFixed(4)+'/unit</span></div>'+(cond>0?'<div class="ccRow"><span>Selected condiments</span><span>₹'+cond.toFixed(4)+'/unit</span></div>':'<div class="ccRow"><span>Selected condiments</span><span>₹0.0000/unit</span></div>')+'<div class="ccRow"><span>+ Spoilage ('+spoil+'%)</span><span>₹'+final.toFixed(4)+'/unit</span></div>'}
function all(){if(Array.isArray(window.BOBS_METHOD2_RM_RECIPES)&&window.BOBS_METHOD2_RM_RECIPES.length)recipes=window.BOBS_METHOD2_RM_RECIPES;window.BOBS_METHOD2_RM_RECIPES=recipes;CAT_ORDER.forEach(cat=>ITEM_DATA[cat].forEach((item,i)=>{if(item.eligible)showChain(cat,i)}));refresh()}
async function load(){try{const q=await jsonp(VAULT+'?action=moduleGet&outletId='+RM.outletId+'&module='+RM.module+'&recordKey='+RM.recordKey);const a=parse(q);if(!a||!a.length)throw new Error('Recipe Master response did not contain recipes');recipes=a;window.BOBS_METHOD2_RM_RECIPES=recipes;all()}catch(e){window.BOBS_RM_ERROR=e;window.BOBS_METHOD2_RM_RECIPES=recipes;all()}}
window.BOBS_METHOD2_RM_RECALC=all;
document.addEventListener('bobs-method2-condiment-change',()=>setTimeout(all,20));
document.addEventListener('input',e=>{if(e.target.matches&&e.target.matches('.qtyInput,.spoilInput'))setTimeout(all,0)});
const spoilScript=document.createElement('script');spoilScript.src='method2-spoilage-ui.js?v=2026-09-13-1';spoilScript.defer=true;document.head.appendChild(spoilScript);
load();
})();
