(function(){'use strict';window.BOBS_SALARY_STARTED=true;
const q=new URLSearchParams(location.search),outlet=q.get('outlet'),stage=q.get('stage')==='salary'?'salary':'baseline',id=q.get('position'),token=q.get('token'),key=stage+'-'+id,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let F,P,S,V,norms,position,pkg,old,staff,dirty=false,busy=false,ready=false,editing='',editDraft=null,preview=null,generation=0,contextCleanup=()=>{},channel;
const money=v=>Number.isFinite(v)?'₹'+v.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2}):'Not calculated';
const link=(url,text)=>{try{const u=new URL(url);return u.protocol==='https:'?'<a href="'+esc(u.href)+'" target="_blank" rel="noopener">'+esc(text)+' ↗</a>':esc(text)}catch(e){return esc(text)}};
function message(id,text,focus=false,tone='info'){const e=$(id);e.dataset.tone=tone;e.textContent=text;if(focus){e.focus();e.scrollIntoView({block:'center'})}}
function changed(){dirty=true;$('salaryReviewed').checked=false;message('salaryActionStatus','Unsaved changes — review the updated summary, then save to Google.');}
function componentLink(k,label){return '<a class="salary-component-link" href="#component='+encodeURIComponent(k)+'">'+esc(label)+'</a>'}
function row(k,label,value,basis='',off=false){return '<tr class="'+(off?'salary-row-muted':'')+'"><td>'+componentLink(k,label)+(basis?'<span class="salary-basis">'+esc(basis)+'</span>':'')+'</td><td>'+money(value)+'</td></tr>'}
const total=(label,v)=>'<tr class="salary-total-row"><td>'+esc(label)+'</td><td>'+money(v)+'</td></tr>';
function render(){
 let value=null,assumptions=[];try{preview=S.preview($('salaryThp').value,pkg,norms,P);({value,assumptions}=preview);message('salaryPreview','')}catch(e){preview=null;message('salaryPreview',e.message,false,'error');}
 const p=pkg,r=norms.payrollRules,con=p.payType==='consolidated';assumptions=assumptions.filter(x=>!x.startsWith('Eligibility, qualifying wages'));
 $('salaryAssumptions').innerHTML=(assumptions.length?'<strong>Preview — eligibility review required</strong><ul>'+assumptions.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':'<strong>Salary planning summary</strong>')+'<small>Company norms from Google; government references recorded '+esc(r.verifiedOn)+'. This preview does not save or certify compliance. '+(dirty?'Changes are not saved.':'')+'</small>';
 $('salaryTotals').innerHTML=[['Gross salary',value?.gross],['Employee deductions',value?.deductions],['Take-home',value?.net],['Monthly CTC',value?.ctc]].map(([k,v],i)=>'<div class="'+(i===3?'salary-ctc':'')+'">'+k+'<strong>'+money(v)+'</strong></div>').join('');
 let earnings=row('basic',con?'Consolidated pay':'Basic',value?.basic,con?'Single pay amount':p.basicPct+'% of gross · company setting')+row('da','DA — Dearness allowance',value?.da,con?'Excluded for consolidated structure':p.da.enabled?(p.da.basis==='percentBasic'?p.da.value+'% of Basic':'₹'+p.da.value+' / month')+' · company setting':'Not included · applicable government rate not yet verified',!p.da.enabled||con)+row('hra','HRA — House rent allowance',value?.hra,con?'Excluded for consolidated structure':p.hraPct+'% of Basic · company setting')+row('special','Special / balancing allowance',value?.special,'Remaining gross salary after the other earnings');
 let deductions=row('pf','Employee PF',value?.employeePf,'Selected rate '+p.employeePfRate+'% · coverage '+(p.pf||'needs review'))+row('esi','Employee ESI',value?.employeeEsi,'Government reference '+r.employeeEsiRate*100+'% · coverage '+(p.esi||'needs review'))+row('tax','Professional tax',value?.professionalTax,'Local schedule / company provision');
 let employer=row('pf','Employer EPF',value?.employerEpf,'Employer PF contribution after pension split')+row('pf','Employer EPS / pension',value?.employerEps,'Within employer PF, not an additional contribution')+row('pf','EDLI',value?.edli,r.edliRate*100+'% government reference')+row('pf','PF administration',value?.admin,r.adminRate*100+'% reference · per-person planning provision')+row('esi','Employer ESI',value?.employerEsi,r.employerEsiRate*100+'% government reference');
 const excluded={earning:[],deduction:[],employer:[]};
 p.components.forEach(x=>{const n=value?.components.find(c=>c.id===x.id)?.monthly,basis=x.enabled?(x.basis==='annual'?'₹'+x.value+' / year ÷ 12':x.basis==='percentGross'?x.value+'% of gross':'₹'+x.value+' / month')+' · company setting':'Not included',html=row('custom:'+x.id,x.name,n,basis,!x.enabled);if(!x.enabled)excluded[x.kind].push(html);else if(x.kind==='earning')earnings+=html;else if(x.kind==='deduction')deductions+=html;else employer+=html});
 const extras=(kind)=>excluded[kind].length?'<tr><td colspan="2"><details class="salary-excluded"><summary>Excluded components ('+excluded[kind].length+') — review / include</summary><table><tbody>'+excluded[kind].join('')+'</tbody></table></details></td></tr>':'';
 $('salaryEarnings').innerHTML=earnings+total('Gross salary',value?.gross)+extras('earning');$('salaryDeductions').innerHTML=deductions+total('Total employee deductions',value?.deductions)+total('Net take-home',value?.net)+extras('deduction');$('salaryEmployer').innerHTML=employer+total('Employer additions & benefits',value?.employerAdditions)+extras('employer');
 $('salaryCtcExplanation').textContent=value?'Gross '+money(value.gross)+' + employer additions '+money(value.employerAdditions)+' = monthly CTC '+money(value.ctc)+'. Outlet daily cost ÷ 31 = '+money(value.daily)+'.':'CTC is incomplete. Review the highlighted input; amounts are not treated as zero.';
}
const number=(id,label,value,extra='')=>'<label>'+esc(label)+'<input id="'+id+'" type="number" step="any" '+(/min=/.test(extra)?'':'min="0"')+' value="'+esc(value??'')+'" '+extra+'></label>';
const text=(id,label,value)=>'<label>'+esc(label)+'<input id="'+id+'" value="'+esc(value??'')+'"></label>';
const check=(id,label,value)=>'<label><input id="'+id+'" type="checkbox" '+(value?'checked':'')+'>'+esc(label)+'</label>';
const select=(id,label,value,options)=>'<label>'+esc(label)+'<select id="'+id+'">'+options.map(([k,v])=>'<option value="'+esc(k)+'" '+(String(value)===k?'selected':'')+'>'+esc(v)+'</option>').join('')+'</select></label>';
const yesno=[['','Review eligibility'],['yes','Yes — covered'],['no','No — record reason']];
function reference(body){return '<div class="salary-reference">'+body+'</div>'}
function dialogControls(){const d=$('salaryComponentBody');if(editing==='pf'){const covered=$('pf').value==='yes';d.querySelectorAll('[data-pf]').forEach(e=>e.disabled=!covered);$('pfReason').disabled=covered;$('reducedPfReason').disabled=!covered||$('pfCategory').value!=='reduced';const rate=norms.payrollRules[$('pfCategory').value==='reduced'?'reducedPfRate':'employeePfRate']*100;for(const k of ['employee','employer']){$(k+'PfRate').min=rate;$(k+'PfLabel').textContent='Government reference '+rate+'%. Your selected rate may be higher.';}}
 if(editing==='esi'){const covered=$('esi').value==='yes';d.querySelectorAll('[data-esi]').forEach(e=>e.disabled=!covered);$('esiReason').disabled=covered;$('esiAverageDailyWage').disabled=!covered||!$('esiEmployeeExempt').checked;}
 if(editing==='da'){$('daValue').disabled=!$('daEnabled').checked;$('daBasis').disabled=!$('daEnabled').checked;}
 if(editing.startsWith('custom:')||editing==='new'){const enabled=$('componentEnabled').checked;d.querySelectorAll('[data-company-input]').forEach(e=>e.disabled=!enabled);}}
function openComponent(k){if(!ready||busy)return;const r=norms.payrollRules,p=pkg;editing=k;editDraft=null;let title='',body='',info=reference('Company setting. '+link(norms.source?.url,'View saved company norms')+'. The government does not prescribe one universal percentage for this component.');
 $('salaryComponentRemove').hidden=true;$('salaryComponentApply').hidden=false;
 if(k==='basic'||k==='hra'){title=k==='basic'?'Basic salary':'HRA — House rent allowance';const field=k==='basic'?'basicPct':'hraPct';body=info+number(field,k==='basic'?'Basic % of gross':'HRA % of Basic',p[field],'max="100"')+'<p>The summary keeps your entered take-home unchanged and recalculates the package.</p>';if(p.payType==='consolidated'){body=reference('Consolidated pay is selected. Turn it off in the summary to use separate Basic/HRA settings.');$('salaryComponentApply').hidden=true;}}
 else if(k==='da'){title='DA — Dearness allowance';body=reference('Applicable government DA rate: not yet verified for this role and outlet. No statutory percentage has been invented. Enter a reviewed company provision; confirm the applicable wage notification separately.')+check('daEnabled','Include DA',p.da.enabled)+select('daBasis','Calculate DA as',p.da.basis,[['percentBasic','% of Basic'],['monthly','₹ per month']])+number('daValue','Selected percentage / amount',p.da.value)+text('daNote','Source / reason for your selected value',p.da.note||'');if(p.payType==='consolidated'){body=reference('Consolidated pay is selected. Turn it off in the summary to use a separate DA component.');$('salaryComponentApply').hidden=true;}}
 else if(k==='special'){title='Special / balancing allowance';body=reference('Calculated automatically: gross salary − Basic − DA − HRA − other cash allowances. Edit those components to change the split while keeping your take-home target.');$('salaryComponentApply').hidden=true;}
 else if(k==='tax'){title='Professional tax';body=reference('Review the applicable local schedule. This saved company amount is a planning provision, not a universal government percentage.')+number('professionalTax','Monthly professional tax ₹',p.professionalTax);}
 else if(k==='pf'){title='PF / pension contributions';body=reference('Government reference recorded '+esc(r.verifiedOn)+'. Ceiling ₹'+esc(r.pfCeiling)+'. '+link(r.pfSource,'Official contribution rates')+' · '+link(r.ceilingSource,'Ceiling reference')+'. EPS '+r.epsRate*100+'% is within employer PF. EDLI '+r.edliRate*100+'%; administration '+r.adminRate*100+'%. Administration minimums may need separate establishment allocation.')+select('pf','PF applies?',p.pf,yesno)+text('pfReason','Reason PF does not apply',p.pfReason)+select('pfCategory','Establishment category',p.pfCategory,[['standard','Standard rate'],['reduced','Eligible reduced rate']])+text('reducedPfReason','Reduced-rate eligibility basis',p.reducedPfReason)+select('eps','EPS membership applies?',p.eps,[['','Review membership'],['yes','Yes'],['no','No — employer share stays EPF']])+number('pfWagePct','PF qualifying wages % of gross',p.payType==='consolidated'?100:p.pfWagePct,'min="50" max="100"')+number('employeePfRate','Selected employee PF %',p.employeePfRate,'max="100"')+'<small id="employeePfLabel"></small>'+number('employerPfRate','Selected employer PF %',p.employerPfRate,'max="100"')+'<small id="employerPfLabel"></small>'+check('higherPf','Agreement confirmed for contributions above the ceiling',p.higherPf)+'<p>Qualifying wage percentage is your reviewed calculation assumption; it is not a government fixed percentage.</p>';}
 else if(k==='esi'){title='ESI contributions';body=reference('Government reference recorded '+esc(r.verifiedOn)+': employee '+r.employeeEsiRate*100+'%, employer '+r.employerEsiRate*100+'%; general wage ceiling ₹'+esc(r.esiCeiling)+'. '+link(r.esiSource,'Official ESI rules')+'. Extra company insurance benefits can be edited separately.')+select('esi','ESI applies?',p.esi,yesno)+text('esiReason','Reason ESI does not apply',p.esiReason)+number('employeeEsiRate','Government employee ESI %',r.employeeEsiRate*100,'readonly')+number('employerEsiRate','Government employer ESI %',r.employerEsiRate*100,'readonly')+number('esiWagePct','ESI qualifying wages % of gross',p.esiWagePct,'min="50" max="100"')+check('esiContinuation','Continuing coverage above the ceiling for this contribution period is confirmed',p.esiContinuation)+check('esiEmployeeExempt','Employee qualifies for low daily-wage exemption',p.esiEmployeeExempt)+number('esiAverageDailyWage','Verified average daily ESI wage ₹',p.esiAverageDailyWage)+'<p>Employee exemption reference ₹'+esc(r.esiDailyExemption)+' per day. Qualifying wages and exemption must be verified.</p>';}
 else if(k==='new'||k.startsWith('custom:')){editDraft=k==='new'?{id:'custom-'+crypto.randomUUID(),name:'Additional company benefit',kind:'employer',basis:'monthly',value:0,enabled:true}:V.clone(p.components.find(x=>x.id===k.slice(7)));if(!editDraft)return;title=k==='new'?'Add a salary component':editDraft.name;const x=editDraft;body=reference('Company component — editable. It is not a fixed statutory rate. Annual provisions are divided by 12; cash allowances are included within gross salary.')+check('componentEnabled','Include this component',x.enabled)+text('componentName','Component name',x.name)+select('componentKind','Component type',x.kind,[['earning','Cash allowance within gross'],['deduction','Employee deduction'],['employer','Employer expense / benefit']])+select('componentBasis','Calculation basis',x.basis,[['monthly','₹ per month'],['annual','₹ per year'],['percentGross','% of gross salary']])+number('componentValue','Selected amount / percentage',x.value);$('salaryComponentRemove').hidden=k==='new';}
 else return;
 $('salaryComponentTitle').textContent=title;$('salaryComponentBody').innerHTML=body;message('salaryComponentError','');
 if(k==='pf'){for(const id of ['pfCategory','eps','pfWagePct','employeePfRate','employerPfRate','higherPf'])$(id).dataset.pf='';$('pfCategory').addEventListener('change',()=>{const n=r[$('pfCategory').value==='reduced'?'reducedPfRate':'employeePfRate']*100;$('employeePfRate').value=n;$('employerPfRate').value=n;dialogControls()});}
 if(k==='esi')for(const id of ['esiWagePct','esiContinuation','esiEmployeeExempt'])$(id).dataset.esi='';
 if(editDraft)for(const id of ['componentName','componentKind','componentBasis','componentValue'])$(id).dataset.companyInput='';
 if(!$('salaryComponentApply').hidden)dialogControls();if(!$('salaryComponentDialog').open)$('salaryComponentDialog').showModal();
 const first=$('salaryComponentBody').querySelector('input:not([disabled]),select:not([disabled])');first?.focus();
}
function closeComponent(){if($('salaryComponentDialog').open)$('salaryComponentDialog').close();if(location.hash.startsWith('#component='))history.replaceState(null,'',location.pathname+location.search);editing='';editDraft=null;}
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#component="]');if(!a)return;e.preventDefault();const k=decodeURIComponent(a.hash.slice(11));history.replaceState(null,'',a.hash);openComponent(k)});
window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#component='))openComponent(decodeURIComponent(location.hash.slice(11)));else closeComponent()});
$('salaryComponentClose').onclick=closeComponent;$('salaryComponentDialog').addEventListener('cancel',e=>{e.preventDefault();closeComponent()});$('salaryComponentBody').addEventListener('input',dialogControls);
function applyComponent(e){e.preventDefault();const candidate=V.clone(pkg),v=id=>$(id).value,c=id=>$(id).checked;
 try{if(['basic','hra'].includes(editing))candidate[editing==='basic'?'basicPct':'hraPct']=v(editing==='basic'?'basicPct':'hraPct');else if(editing==='da')candidate.da={enabled:c('daEnabled'),basis:v('daBasis'),value:v('daValue'),note:v('daNote')};else if(editing==='tax')candidate.professionalTax=v('professionalTax');else if(editing==='pf'){for(const k of ['pf','pfReason','pfCategory','reducedPfReason','eps','pfWagePct','employeePfRate','employerPfRate'])candidate[k]=v(k);candidate.higherPf=c('higherPf');}else if(editing==='esi'){for(const k of ['esi','esiReason','esiWagePct','esiAverageDailyWage'])candidate[k]=v(k);for(const k of ['esiContinuation','esiEmployeeExempt'])candidate[k]=c(k);}else if(editDraft){const component={...editDraft,enabled:c('componentEnabled'),name:v('componentName').trim(),kind:v('componentKind'),basis:v('componentBasis'),value:v('componentValue')};if(editing==='new')candidate.components.push(component);else candidate.components[candidate.components.findIndex(x=>x.id===component.id)]=component;}
 candidate.eligibilityConfirmed=false;S.preview($('salaryThp').value,candidate,norms,P);pkg=candidate;$('salaryEligibility').checked=false;changed();render();closeComponent();message('salaryActionStatus','Component updated. Review the revised totals, confirm eligibility and save the package.');
 }catch(err){message('salaryComponentError',err.message,true,'error')}}
$('salaryComponentForm').onsubmit=applyComponent;$('salaryComponentRemove').onclick=()=>{if(!editDraft||!confirm('Remove '+editDraft.name+' from this draft? Earlier saved versions remain in Google history.'))return;pkg.components=pkg.components.filter(x=>x.id!==editDraft.id);changed();render();closeComponent()};
$('addSalaryComponent').onclick=()=>openComponent('new');
$('salaryThp').addEventListener('input',()=>{changed();pkg.eligibilityConfirmed=false;$('salaryEligibility').checked=false;render()});
$('consolidated').onchange=()=>{pkg.payType=$('consolidated').checked?'consolidated':'structured';if($('consolidated').checked){pkg.components.forEach(x=>x.enabled=false);pkg.da.enabled=false;}pkg.eligibilityConfirmed=false;$('salaryEligibility').checked=false;changed();render()};
$('salaryEligibility').onchange=()=>{pkg.eligibilityConfirmed=$('salaryEligibility').checked;changed();try{preview=S.preview($('salaryThp').value,pkg,norms,P)}catch(e){preview=null}};$('salaryCalculate').onclick=()=>{render();message('salaryActionStatus',preview?'Summary recalculated. '+(preview.assumptions.length?'Confirm the listed eligibility details before saving.':'Review the totals, then save.'):'Review the highlighted calculation error.',true)};
async function deliverSaved(message){if(!token){BOBS_WINDOW_RETURN.notify(message,['bobs-salary-package']);return false;}return new Promise((resolve,reject)=>{let bridge,finished=false;const done=(ok,error)=>{if(finished)return;finished=true;clearTimeout(timer);window.removeEventListener('message',receive);try{bridge?.close()}catch(e){}if(error)reject(Error(error));else resolve(ok)};const accept=m=>{if(m?.type==='bobs-salary-package-applied'&&m.token===token)done(m.ok,m.ok?null:m.error||'The outlet draft needs review.')};function receive(e){try{if(e.origin===location.origin&&e.source===window.opener)accept(e.data)}catch(err){}}window.addEventListener('message',receive);const timer=setTimeout(()=>done(false),80000);try{if(window.BroadcastChannel){bridge=new BroadcastChannel('bobs-salary-context');bridge.onmessage=e=>accept(e.data)}}catch(e){}BOBS_WINDOW_RETURN.notify(message,['bobs-salary-package','bobs-salary-context']);});}
function requestPosition(){contextCleanup();return new Promise(resolve=>{let done=false,interval,timeout;const finish=p=>{if(done)return;done=true;clearInterval(interval);clearTimeout(timeout);window.removeEventListener('message',receive);try{channel?.close()}catch(e){}channel=null;resolve(p)};const accept=m=>{if(m?.type==='bobs-salary-position'&&m.token===token&&m.position?.id===id)finish(m.position)};function receive(e){if(e.origin!==location.origin)return;try{if(window.opener&&e.source===window.opener)accept(e.data)}catch(err){}}window.addEventListener('message',receive);try{if(token&&window.BroadcastChannel){channel=new BroadcastChannel('bobs-salary-context');channel.onmessage=e=>accept(e.data)}}catch(e){}const send=()=>{const m={type:'bobs-salary-request',token,positionId:id,stage,outlet};try{window.opener?.postMessage(m,location.origin)}catch(e){}try{channel?.postMessage(m)}catch(e){}};contextCleanup=()=>finish(null);if(!token)return finish(null);interval=setInterval(send,500);timeout=setTimeout(()=>finish(null),8000);send()})}
async function load(){if(busy)return;const at=++generation;ready=false;$('salaryFields').disabled=true;$('salaryRetry').hidden=true;message('salaryStatus','Loading Google salary rules and your selected position…');
 try{F=window.BOBS_OUTLET_FLOW;P=window.BOBS_SALARY_PACKAGE;S=window.BOBS_SALARY_SUMMARY;V=window.BOBS_VERIFIED;if(!F||!P||!S||!V)throw Error('A salary page script did not load. Refresh this window, then retry.');if(!outlet||!id||!/^[-\w]{1,80}$/.test(id))throw Error('Open Review / edit salary package from an outlet staff position.');const pending=requestPosition();
 const read=async(o,m,k,label)=>{try{return await V.read(o,m,k)}catch(e){throw Error(label+': '+e.message)}};
 const loaded=await Promise.all([read('COMPANY','THP_NORMS','default','Google salary rules'),read(outlet,'OUTLET_SALARY_PACKAGES',key,'Saved salary package'),read('COMPANY','STAFF_MASTER','default','Staff Master')]);if(at!==generation)return;[norms,old,staff]=loaded;position=await pending;if(at!==generation)return;if(!position){const parent=await read(outlet,stage==='baseline'?'OUTLET_BASELINE':'OUTLET_STAFFING','default','Saved outlet position');if(at!==generation)return;position=parent?.positions?.find(x=>x.id===id);if(!position&&old)position=old.budget;}
 if(!position)throw Error('The selected position is unsaved and this window could not connect to the outlet page. Keep that page open, then Retry; or return and reopen Review / edit salary package.');if(position.staffId){const employee=staff?.staff?.find(x=>String(x.staffId)===String(position.staffId));if(!employee)throw Error('Linked employee is unavailable in Staff Master.');position={...position,takeHome:employee.takeHome??employee.salaryBreakdown?.target,salaryPackage:employee.salaryPackage};}
 P.defaults(norms);pkg=S.draft(position.salaryPackage,P,norms);if(position.salaryBreakdown&&Number(position.takeHome)!==Number(position.salaryBreakdown.target))pkg.eligibilityConfirmed=false;$('salaryThp').value=position.takeHome??'';$('consolidated').checked=pkg.payType==='consolidated';$('salaryEligibility').checked=!!pkg.eligibilityConfirmed;$('salaryReviewed').checked=false;ready=true;$('salaryFields').disabled=false;$('salaryContext').textContent='Outlet '+outlet+' · '+(position.role||id)+(position.staffId?' · employee '+position.staffId:' · planned position');$('salarySaveScope').textContent=position.staffId?'Save updates this linked employee’s company Staff Master salary package.':'Save stores this position’s package in Google. After returning, review and save the outlet plan to apply the cost.';for(const [id,url] of [['salaryHistory','salary-history.html?'+new URLSearchParams({outlet,key,stage,returnTo:location.href})],['salaryRecord','google-records.html?'+new URLSearchParams({outlet,module:'OUTLET_SALARY_PACKAGES',key})]]){$(id).href=url;$(id).hidden=false;}message('salaryStatus','Google rules loaded. Review the summary; select any component to edit.');render();if(location.hash.startsWith('#component='))openComponent(decodeURIComponent(location.hash.slice(11)));
 }catch(e){if(at!==generation)return;ready=false;$('salaryFields').disabled=true;contextCleanup();message('salaryStatus','Salary summary could not load. '+e.message,true,'error');$('salaryRetry').hidden=false;}}
$('salaryRetry').onclick=()=>{if(!window.BOBS_SALARY_SUMMARY||!window.BOBS_SALARY_PACKAGE)location.reload();else load()};
$('salaryForm').onsubmit=async e=>{e.preventDefault();if(!ready||busy)return;let proposalSaved=false;try{pkg.eligibilityConfirmed=$('salaryEligibility').checked;P.calculate($('salaryThp').value,pkg,norms);if(!$('salaryReviewed').checked)throw Error('Tick “I checked the complete package and employer cost” before saving.');busy=true;$('salaryFields').disabled=true;$('salaryCancel').disabled=true;message('salaryActionStatus','Saving to Google and verifying the saved package…',true);const latest=await V.read('COMPANY','THP_NORMS');if(!V.equal(latest,norms))throw Error('Google HR rules changed. Reopen the package to review the latest rules.');const budget=F.useThp({...position,staffId:'',takeHome:$('salaryThp').value,salaryPackage:pkg},norms);const saved=await V.save(outlet,'OUTLET_SALARY_PACKAGES',key,{schema:2,positionId:id,stage,staffId:position.staffId||'',role:position.role||'',budget,history:{hasPrevious:!!old},savedAt:new Date().toISOString()},old);old=saved;proposalSaved=true;
 if(position.staffId){const current=await V.read('COMPANY','STAFF_MASTER');if(!V.equal(current,staff))throw Error('Staff Master changed. Package proposal saved; reopen before applying it to the employee.');const employee=current?.staff?.find(x=>String(x.staffId)===String(position.staffId));if(!employee)throw Error('Linked employee no longer exists.');const next={...current,staff:current.staff.map(x=>x===employee?{...x,takeHome:budget.takeHome,salaryPackage:budget.salaryPackage,salaryBasis:budget.salaryBasis,salaryNorms:budget.salaryNorms,salaryNormsStamp:budget.salaryNormsStamp,salaryBreakdown:budget.salaryBreakdown,monthlyCtc:budget.salaryBreakdown.ctc}:x)};staff=await V.save('COMPANY','STAFF_MASTER','default',next,current);}
 dirty=false;message('salaryActionStatus','Salary package saved and verified in Google. Returning to the outlet…');const m={type:'bobs-salary-package-saved',outlet,stage,positionId:id,key,token};const applied=await deliverSaved(m);busy=false;if(applied){try{window.close();if(window.closed)return;}catch(e){}}BOBS_WINDOW_RETURN.returnToParent('outlet-plan.html?'+new URLSearchParams({outlet,stage,salaryPackageKey:key}),{page:'outlet-plan.html',salaryPackageKey:key});
 }catch(err){message('salaryActionStatus',(proposalSaved?'Proposal saved in Google; completion needs attention: ':'')+err.message,true,'error')}finally{busy=false;$('salaryFields').disabled=false;$('salaryCancel').disabled=false;}};
$('salaryCancel').onclick=()=>{if(dirty&&!confirm('Return without saving these package changes?'))return;dirty=false;BOBS_WINDOW_RETURN.returnToParent('outlet-plan.html?'+new URLSearchParams({outlet:outlet||'',stage}))};window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue=''}});load();
})();
