const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),{JSDOM}=require(process.env.JSDOM_PATH||'jsdom');async function fixture(){const dom=new JSDOM('',{runScripts:'outside-only',url:'https://bobs.test/'}),w=dom.window;w.BOBS_VERIFIED={};for(const p of ['shared_data.js','method2-core.js','bobs-cost-flow.js','idli-support-core.js','bobs-outlet-flow-core.js','bobs-outlet-report.js','bobs-roadmap-core.js','bobs-roadmap-outlet-flow.js'])w.eval(fs.readFileSync(p,'utf8'));await Promise.resolve();const ok=value=>({status:'ok',value}),records=Object.fromEntries(['method1','method2','equipment','workload','workforce','expenses','baseline','staffing','requirements','costAllocations','review','methodFlow','staff','allocation','companyReview','allReviews'].map(k=>[k,ok(null)])),shiftTimes=[{start:'06:00',end:'14:00'}],data={outlet:'1',outlets:ok([{id:'1',name:'RSP',shiftTimes},{id:'2',name:'GP',shiftTimes}]),recipes:ok([]),records},t={M2:w.M2,C:w.BOBS_COST_FLOW,S:w.IdliSupport,catalogue:w.ITEM_DATA};return {dom,w,data,ok,eval:()=>w.BOBS_ROADMAP_CORE.evaluate(data,t)}}
test('roadmap begins with outlet shifts then expenses/counter baseline, not recipes before method choice',async()=>{const f=await fixture(),v=f.eval();assert.match(v.stages[0].title,/Outlet count/);assert.equal(v.stages[0].status,'done');assert.match(v.stages[1].title,/mandatory staff/);assert.equal(v.stages[1].status,'pending');assert.equal(v.next.id,'2');assert.match(v.next.href,/outlet-plan.*baseline/);assert.match(v.stages[6].title,/Item shares/);f.dom.window.close()});
test('verified baseline unlocks method selection; failures remain unknown and no visit earns ticks',async()=>{const f=await fixture(),F=f.w.BOBS_OUTLET_FLOW;f.data.records.baseline=f.ok({reviewed:true,positions:[],noCounter:true,shiftStamp:F.stamp(f.data.outlets.value[0].shiftTimes)});f.data.records.expenses=f.ok({expenses:[]});assert.equal(f.eval().stages[1].status,'done');assert.equal(f.eval().next.id,'3');f.data.records.expenses={status:'error',error:'Google failed'};assert.equal(f.eval().stages[1].status,'unknown');assert.equal(f.eval().stages[9].status,'pending');f.dom.window.close()});
test('shift changes invalidate baseline and point to review rather than zero expenses',async()=>{const f=await fixture(),F=f.w.BOBS_OUTLET_FLOW;f.data.records.baseline=f.ok({reviewed:true,positions:[],noCounter:true,shiftStamp:F.stamp(f.data.outlets.value[0].shiftTimes)});f.data.records.expenses=f.ok({expenses:[]});f.data.outlets.value[0].shiftTimes[0].end='15:00';assert.equal(f.eval().stages[1].status,'review');f.dom.window.close()});

test('read-only report evaluator can load on legacy pages without the protected writer',async()=>{const f=await fixture();delete f.w.BOBS_VERIFIED;assert.doesNotThrow(()=>f.w.eval(fs.readFileSync('bobs-outlet-report.js','utf8')));assert.equal(f.eval().stages.length,10);f.dom.window.close()});

test('Method1-only analysis uses saved Google hourly inputs and reviewed markup plus outlet budgets',async()=>{const f=await fixture(),F=f.w.BOBS_OUTLET_FLOW;const baseline={reviewed:true,positions:[],noCounter:true},data={OUTLET_BASELINE:baseline,FIXED_EXPENSES:{expenses:[{name:'Rent',amount:100}]},METHOD2:null,METHOD1:{rows:[{customers:10,basket:50}]},METHOD_FLOW:{method1:{reviewed:true,markup:25}},staff:null,hr:null};data.METHOD_FLOW.method1.sourceStamp=F.stamp(data.METHOD1);const r=f.w.BOBS_OUTLET_REPORT.calculate(data,'1');assert.equal(r.sales,500);assert.equal(r.direct,400);assert.equal(r.profit,0);assert.equal(r.breakEven,500);data.METHOD1.rows[0].customers=11;assert.throws(()=>f.w.BOBS_OUTLET_REPORT.calculate(data,'1'),/verify Method1/);f.dom.window.close()});

test('capital roadmap completion requires a current saved budget; stale and failed reads never earn a tick',async()=>{const f=await fixture(),w=f.w,F=w.BOBS_OUTLET_FLOW;w.eval(fs.readFileSync('bobs-capital-core.js','utf8'));const K=w.BOBS_CAPITAL,raw={itemEditors:{'Breakfast Catalogue::0':{mode:'production',unit:'piece',batchSize:10,batches:1,condiments:[]}}};f.data.records.method2=f.ok(raw);const items=F.selected(w.M2.state(raw),w.ITEM_DATA,w.M2),assets={reviewed:true,sourceStamp:K.assetSource(items,[],F,w.M2),assets:[],noAssets:true,noAssetsReason:'Explicitly reviewed fixture'};f.data.records.assets=f.ok(assets);const node=()=>f.eval().stages[8].children.find(x=>x.id==='capital-expenditure');assert.equal(node().status,'pending');const inputs={reviewed:true};f.data.records.capitalExpenditure=f.ok({reviewed:true,sourceStamp:K.capitalSource(assets,items,[],F,w.M2),inputs,result:K.capitalBudget(assets,items,inputs)});assert.equal(node().status,'done');assets.noAssetsReason='Changed reason';assert.equal(node().status,'review');f.data.records.capitalExpenditure={status:'error',error:'Google unavailable'};assert.equal(node().status,'unknown');w.close();});
