const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs');
const P=require('../bobs-salary-package-core.js'),S=require('../bobs-salary-summary-core.js'),norms={...require('./fixtures/thp-norms.json'),payrollRules:require('./fixtures/payroll-rules.json')};
const approved=()=>({...S.draft(null,P,norms),pf:'yes',eps:'yes',esi:'yes',eligibilityConfirmed:true}),near=(a,b)=>assert(Math.abs(a-b)<1e-6,`${a} != ${b}`);
test('first THP preview reconciles without claiming eligibility or mutating Google norms/package',()=>{const p=S.draft(null,P,norms),before=JSON.stringify({p,norms});const r=S.preview(1500,p,norms,P);near(r.value.net,1500);near(r.value.ctc,r.value.gross+r.value.employerAdditions);assert(r.assumptions.length>=3);assert.equal(JSON.stringify({p,norms}),before);assert.throws(()=>P.calculate(1500,p,norms),/eligibility/);});
test('DA is part of gross, not an extra employer charge; percentage and monthly basis reconcile',()=>{const p=approved(),base=P.calculate(15000,p,norms);p.da={enabled:true,basis:'percentBasic',value:10};const r=P.calculate(15000,p,norms);near(r.da,r.basic*.1);near(r.basic+r.da+r.hra+r.special+r.earnings,r.gross);near(r.ctc,base.ctc);near(r.net,15000);p.da={enabled:true,basis:'monthly',value:250};near(P.calculate(15000,p,norms).da,250);p.da.value=90000;assert.throws(()=>P.calculate(15000,p,norms),/exceed/);});
test('existing package calculation shape and norms remain backward compatible',()=>{const p=approved();delete p.da;const r=P.calculate(15000,p,norms);assert(!('da' in r));const old=require('../bobs-outlet-flow-core.js');P.attach(old);const saved=old.useThp({id:'one',takeHome:15000,salaryPackage:p},norms);near(old.fund({positions:[saved]},null,null,'1',norms).positions[0].salaryBreakdown.ctc,r.ctc);});
test('preview above general ESI ceiling is explicitly provisional and does not fake continuing coverage',()=>{const p=S.draft(null,P,norms),r=S.preview(40000,p,norms,P);assert(r.assumptions.some(x=>/ESI excluded/.test(x)));assert.equal(r.value.employeeEsi,0);assert.equal(p.esi,'');assert.equal(p.esiContinuation,false);});
test('consolidated calculation excludes DA and keeps actual statutory coverage',()=>{const p=approved();p.da={enabled:true,basis:'monthly',value:500};p.payType='consolidated';const r=P.calculate(15000,p,norms);assert.equal(r.da,0);assert(r.employeePf>0);assert(r.employeeEsi>0);near(r.basic+r.earnings,r.gross);});

const {JSDOM}=require(process.env.JSDOM_PATH||'jsdom');
async function fixture({fail=false,parent=false}={}){const dom=new JSDOM(fs.readFileSync('salary-editor.html','utf8'),{url:'https://bobs.test/salary-editor.html?outlet=1&stage=baseline&position=Mandatory1'+(parent?'&token=test-token':''),runScripts:'outside-only'}),w=dom.window,reads=[],writes=[];w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.confirm=()=>true;let failed=fail;const pos={id:'Mandatory1',role:'Cashier',takeHome:1500};w.BOBS_VERIFIED={clone:x=>JSON.parse(JSON.stringify(x)),equal:(a,b)=>JSON.stringify(a)===JSON.stringify(b),read:async(o,m)=>{reads.push(m);if(failed&&m==='THP_NORMS')throw Error('Fixture Google unavailable');if(m==='THP_NORMS')return structuredClone(norms);if(m==='OUTLET_BASELINE')return {positions:parent?[]:[pos]};return null},save:async(...args)=>{writes.push(args);return args[3]}};w.BOBS_WINDOW_RETURN={notify(){},returnToParent(){}};
 if(parent)w.BroadcastChannel=class{postMessage(m){if(m.type==='bobs-salary-request')queueMicrotask(()=>this.onmessage?.({data:{type:'bobs-salary-position',token:m.token,position:pos}}))}close(){}};
 for(const file of ['bobs-outlet-flow-core.js','bobs-salary-package-core.js','bobs-salary-summary-core.js','salary-editor.js'])w.eval(fs.readFileSync(file,'utf8'));
 for(let n=0;n<20;n++){await new Promise(r=>setImmediate(r));if(!w.document.getElementById('salaryFields').disabled||!w.document.getElementById('salaryRetry').hidden)break}
 const $=id=>w.document.getElementById(id),click=k=>w.document.querySelector('a[href="#component='+k+'"]')?.click();return {dom,w,$,click,reads,writes,recover(){failed=false}};
}
test('salary page opens full summary; linked DA edits update displayed package and save stays gated',async()=>{const f=await fixture();try{assert.equal(f.$('salaryFields').disabled,false);assert.match(f.$('salaryTotals').textContent,/1,500.00/);assert.match(f.$('salaryAssumptions').textContent,/Preview/);f.click('da');assert(f.$('salaryComponentDialog').open);f.$('daEnabled').checked=true;f.$('daEnabled').dispatchEvent(new f.w.Event('input',{bubbles:true}));f.$('daValue').value='5';f.$('salaryComponentForm').dispatchEvent(new f.w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(f.$('salaryComponentDialog').open,false);assert.match(f.$('salaryEarnings').textContent,/5% of Basic/);f.$('salaryForm').dispatchEvent(new f.w.Event('submit',{cancelable:true}));await new Promise(r=>setImmediate(r));assert.equal(f.writes.length,0);assert.match(f.$('salaryActionStatus').textContent,/eligibility/);assert.equal(f.w.document.activeElement.id,'salaryActionStatus');}finally{f.dom.window.close()}});
test('failed Google load shows working retry and recovers without writes',async()=>{const f=await fixture({fail:true});try{assert(f.$('salaryFields').disabled);assert.equal(f.$('salaryRetry').hidden,false);assert.match(f.$('salaryStatus').textContent,/Google salary rules/);f.recover();f.$('salaryRetry').click();for(let i=0;i<20;i++)await new Promise(r=>setImmediate(r));assert.equal(f.$('salaryFields').disabled,false);assert.match(f.$('salaryTotals').textContent,/1,500.00/);assert.equal(f.writes.length,0);}finally{f.dom.window.close()}});
test('opener-less salary window receives unsaved position through same-origin channel',async()=>{const f=await fixture({parent:true});try{assert.equal(f.$('salaryFields').disabled,false);assert.equal(f.reads.includes('OUTLET_BASELINE'),false);assert.match(f.$('salaryContext').textContent,/Cashier/);assert.equal(f.writes.length,0);}finally{f.dom.window.close()}});
