const {test}=require('node:test'),assert=require('node:assert/strict');
const F=require('../bobs-outlet-flow-core.js'),P=require('../bobs-salary-package-core.js'),K=require('../bobs-capital-core.js'),C=require('../bobs-cost-flow.js');
require('../method2-core.js');const M=globalThis.M2;
P.attach(F);
const norms={...require('./fixtures/thp-norms.json'),payrollRules:require('./fixtures/payroll-rules.json')},clone=x=>structuredClone(x),near=(a,b)=>assert(Math.abs(a-b)<.001,`${a} != ${b}`);
function pkg(){return {...P.defaults(norms),pf:'yes',eps:'yes',esi:'yes',eligibilityConfirmed:true}}
test('official defaults require explicit eligibility; reverse salary reconciles rounded contributions',()=>{assert.throws(()=>P.calculate(15000,P.defaults(norms),norms),/eligibility/);const p=pkg(),x=P.calculate(15000,p,norms);near(x.net,15000);near(x.ctc,15000+x.deductions+x.employerAdditions);near(x.daily,x.ctc/31);assert.equal(x.employeePf,Math.round(Math.min(x.pfQualifying,25000)*.12));assert.equal(x.employeeEsi,Math.ceil(x.esiWage*.0075));assert.equal(x.employerEsi,Math.ceil(x.esiWage*.0325));near(x.employerEpf+x.employerEps,x.employerPf)});
test('PF permits higher contributions, enforces minimum and reduced category explanation',()=>{const p=pkg();p.employeePfRate=11;assert.throws(()=>P.calculate(15000,p,norms),/percentage/);p.employeePfRate=14;assert(P.calculate(15000,p,norms).employeePf>P.calculate(15000,pkg(),norms).employeePf);p.pfCategory='reduced';p.employeePfRate=p.employerPfRate=10;assert.throws(()=>P.calculate(15000,p,norms),/basis/);p.reducedPfReason='Verified applicable establishment';near(P.calculate(15000,p,norms).net,15000)});
test('consolidated pay preserves statutory coverage and supports optional cash allowances',()=>{const p=pkg();p.payType='consolidated';p.components.forEach(x=>x.enabled=false);p.components.push({id:'travel',name:'Travel allowance',kind:'earning',basis:'monthly',value:500,enabled:true});const x=P.calculate(15000,p,norms);assert(x.employeePf>0&&x.employeeEsi>0);near(x.basic+500,x.gross);assert.equal(x.benefits,0);p.pf='no';assert.throws(()=>P.calculate(15000,p,norms),/why PF/)});
test('ESI above ceiling and daily-wage exemption require explicit supporting inputs',()=>{const p=pkg();assert.throws(()=>P.calculate(40000,p,norms),/continuing/);p.esiContinuation=true;const x=P.calculate(40000,p,norms);assert.equal(x.employeePf,3000);p.esiEmployeeExempt=true;p.esiAverageDailyWage=200;assert.throws(()=>P.calculate(40000,p,norms),/daily-wage/);p.esiAverageDailyWage=176;const low=P.calculate(4000,p,norms);assert.equal(low.employeeEsi,0);assert(low.employerEsi>0)});
test('annual benefits and extra deductions are allocated once; excluded components cost zero',()=>{const p=pkg();p.components.forEach(x=>x.enabled=false);p.components.push({id:'extra',name:'Deduction',kind:'deduction',basis:'monthly',value:500,enabled:true},{id:'insurance',name:'Annual insurance',kind:'employer',basis:'annual',value:12000,enabled:true});const x=P.calculate(15000,p,norms);near(x.net,15000);assert.equal(x.extraDeductions,500);assert.equal(x.benefits,1000);p.components.at(-1).enabled=false;assert.equal(P.calculate(15000,p,norms).benefits,0)});
test('saved packages reject stale references, tampering and stale actual employee costs',()=>{const p=F.useThp({id:'M1',takeHome:15000,salaryPackage:pkg()},norms),b={positions:[p]};near(F.salary(F.fund(b,null,null,'1',norms).positions[0]),p.salaryBreakdown.ctc);const changed=clone(norms);changed.payrollRules.pfCeiling=26000;assert.throws(()=>F.fund(b,null,null,'1',changed),/changed/);const bad=clone(b);bad.positions[0].salaryBreakdown.ctc=0;assert.throws(()=>F.fund(bad,null,null,'1',norms),/breakdown/);const person={...p,staffId:'E1',monthlyCtc:p.salaryBreakdown.ctc};near(F.salary(F.fund({positions:[{id:'M',staffId:'E1'}]},{staff:[person]},{E1:{1:50}},'1',norms).positions[0]),person.monthlyCtc/2);person.monthlyCtc++;assert.throws(()=>F.fund({positions:[]},{staff:[person]},{E1:{1:50}},'1',norms),/differs/)});
const items=[{key:'a'},{key:'b'}],asset=()=>({assets:[{id:'Grinder1',name:'Shared grinder',quantity:2,ownedQty:1,unitCost:60000,residual:6000,usefulYears:5,annualDays:300,costConfirmed:true,uses:{a:60,b:40}}]});
test('shared assets allocate once; capital purchase excludes owned units',()=>{const t=K.assetTotals(asset(),items);near(t.daily,72);near(t.capex,60000);near(t.assetValue,120000);near(t.items.a,43.2);near(t.items.a+t.items.b,t.daily)});
test('asset review blocks blank assumptions, over-allocation and silent zero machinery',()=>{for(const field of ['unitCost','residual','usefulYears','annualDays']){const a=asset();a.assets[0][field]='';assert.throws(()=>K.assetTotals(a,items),/Enter/)}const a=asset();a.assets[0].uses.b=50;assert.throws(()=>K.assetTotals(a,items),/exceed/);a.assets[0].uses.b=0;assert.throws(()=>K.assetTotals(a,items),/unallocated/);assert.throws(()=>K.assetTotals({assets:[]},items),/Confirm/);assert.equal(K.assetTotals({assets:[],noAssets:true,noAssetsReason:'No machines'},items).daily,0)});
function operatingFixture(){const item={name:'Idli',recipeName:'Idli'},d={mode:'production',unit:'piece',batchSize:10,batches:1,sold:5,price:100,spoilage:0,uuwp:0,markup:25,pricingBasis:'markup',condiments:[],recipeOverrides:{},mainPacking:{packingMode:'none',packaging:[]},commonPacking:{packingMode:'none',packaging:[]}},recipe={name:'Idli',yieldQty:10,yieldUnit:'piece',ingredients:[['Rice',1,'kg',100]]},items=[{key:'Breakfast Catalogue::0',item,d}],baseline={reviewed:true,positions:[{id:'Cashier',role:'Cashier',shift:0,takeHome:31000,deductions:0,employerAdditions:0}]},requirements={items:{}},staffing={reviewed:true,salaryReviewed:true,date:C.today(),menuStamp:F.menuStamp(items),recipeStamp:F.recipeStamp(items,[recipe],M),requirementsStamp:F.stamp(requirements),baselineStamp:F.stamp(baseline),positions:[]};return {items,recipes:[recipe],baseline,staffing,requirements,expenses:{expenses:[{id:'rent',name:'Rent',amount:100}]},state:{},staff:null,hr:null,norms};}
test('working-capital inputs use planned production and whole-outlet salary once, without selling markup',()=>{const d=operatingFixture(),before=clone(d.items),r=K.operating(d,'1',F,M,C);near(r.provision,1200);assert.equal(r.lines.filter(x=>x.kind==='labour').length,1);near(r.items[0].food,100);assert.deepEqual(d.items,before);d.items[0].d.price=10000;d.items[0].d.markup=500;near(K.operating(d,'1',F,M,C).provision,1200);d.staffing.date='2000-01-01';assert.throws(()=>K.operating(d,'1',F,M,C),/workforce/)});
test('cash funding distinguishes actual payment from daily reserve and subtracts coverage once',()=>{const op={provision:1200,lines:[{id:'rm',name:'Inputs',kind:'materials',daily:100},{id:'labour',name:'Salary',kind:'labour',daily:1000},{id:'rent',name:'Rent',kind:'operating',daily:100}]},inputs={reviewed:true,lines:{rm:{mode:'reserve',stock:20,credit:30},labour:{mode:'payment',amount:31000},rent:{mode:'payment',amount:0,reason:'Already paid'}},buffer:500,availableCash:10000,receipts:5000};const r=K.workingCapital(op,inputs);near(r.requirement,31550);near(r.additionalFunding,16550);inputs.lines.rm.credit=90;assert.throws(()=>K.workingCapital(op,inputs),/exceed/);inputs.lines.rm.credit=30;inputs.lines.rent.reason='';assert.throws(()=>K.workingCapital(op,inputs),/Explain/)});
test('asset allowance requires current saved product and recipe provenance',()=>{const d=operatingFixture(),a={reviewed:true,assets:[],noAssets:true,noAssetsReason:'Fixture',sourceStamp:K.assetSource(d.items,d.recipes,F,M)};assert.equal(K.depreciation(a,d.items,d.recipes,F,M,d.items[0].key).itemDaily,0);d.recipes[0].ingredients[0][3]=101;assert.throws(()=>K.depreciation(a,d.items,d.recipes,F,M,d.items[0].key),/Review assets/)});
