'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const code=fs.readFileSync('bobs-window-return.js','utf8');
function fixture({href='https://bobs.test/method2-item.html?outlet=2',referrer='',opener=null,closeWorks=true}={}){const calls=[],root={location:{href,origin:'https://bobs.test',assign:u=>calls.push(['navigate',u])},document:{referrer,addEventListener(){}},opener,closed:false,close(){calls.push(['close']);if(closeWorks)this.closed=true},setTimeout:f=>f()};root.top=root;vm.runInNewContext(code,{window:root,URL,console});return {nav:root.BOBS_WINDOW_RETURN,calls,root}}
function parent(href='https://bobs.test/outlet-method-flow.html?from=outlet-setup&outlets=1%2C2'){const p={closed:false,location:{href},focus(){this.focused=true},postMessage(){}};p.top=p;return p}
test('live opener is focused and child closes without navigating parent',()=>{const p=parent(),f=fixture({opener:p});f.nav.returnToParent('method2.html?outlet=2');assert(p.focused);assert.deepEqual(f.calls,[['close']]);assert.equal(p.location.href,'https://bobs.test/outlet-method-flow.html?from=outlet-setup&outlets=1%2C2')});
test('recorded immediate parent retains outlet list and fragment when opener closes',()=>{const p=parent(),f=fixture({opener:p});p.closed=true;f.nav.returnToParent('method2.html?outlet=2');assert.deepEqual(f.calls,[['navigate',p.location.href]])});
test('failed window.close navigates child to recorded parent only',()=>{const p=parent(),f=fixture({opener:p,closeWorks:false});f.nav.returnToParent();assert.deepEqual(f.calls,[['close'],['navigate',p.location.href]])});
test('nested popup carries immediate item URL and its existing parent context',()=>{const parentUrl='https://bobs.test/method2.html?flow=1&outlet=2',href='https://bobs.test/method2-item.html?outlet=2&returnTo='+encodeURIComponent(parentUrl)+'#supplyHeading',f=fixture({href});const child=new URL(f.nav.child('recipe-cost-editor.html?item=Idli&outlet=2'));assert.equal(child.searchParams.get('returnTo'),href);assert.equal(child.searchParams.get('outlet'),'2')});
test('reject external, javascript, credentials, directory traversal and non-page return',()=>{const f=fixture();for(const u of ['https://evil.test/a.html','javascript:alert(1)','https://u:p@bobs.test/a.html','https://bobs.test/x.js'])assert.equal(f.nav.safe(u),null);const nested=fixture({href:'https://bobs.test/BOBS-OUTLETS/method2-item.html'});assert.equal(nested.nav.safe('../outside.html'),null)});
test('standalone auxiliary save stays open while explicit fallback still works',()=>{const f=fixture();assert.equal(f.nav.afterSave(),false);assert.equal(f.calls.length,0);f.nav.afterSave('method2.html?outlet=2');assert.deepEqual(f.calls,[['navigate','https://bobs.test/method2.html?outlet=2']])});
test('referrer supplies safe previous-window fallback',()=>{const f=fixture({referrer:'https://bobs.test/reverse-thp.html?outlet=2'});f.nav.afterSave();assert.deepEqual(f.calls,[['navigate','https://bobs.test/reverse-thp.html?outlet=2']])});
test('notification failures cannot suppress return',()=>{const p=parent();p.postMessage=()=>{throw Error('closed race')};const f=fixture({opener:p});f.nav.notify({type:'saved'},['test']);f.nav.afterSave();assert.deepEqual(f.calls,[['close']])});

test('verified child fallback resumes matching parent details without changing route context',()=>{const f=fixture({href:'https://bobs.test/recipe-cost-editor.html?returnTo='+encodeURIComponent('https://bobs.test/method2-item.html?outlet=2&cat=Breakfast&i=0')});f.nav.afterSave(null,{page:'method2-item.html',hash:'supplyHeading'});assert.deepEqual(f.calls,[['navigate','https://bobs.test/method2-item.html?outlet=2&cat=Breakfast&i=0#supplyHeading']]);const other=fixture({referrer:'https://bobs.test/method2.html?outlet=2'});other.nav.afterSave(null,{page:'method2-item.html',hash:'supplyHeading'});assert.deepEqual(other.calls,[['navigate','https://bobs.test/method2.html?outlet=2']])});
