function saveModuleData_(body){const sheets=ensureSheets_(),sheet=sheets.module,outletId=String(body.outletId||''),module=String(body.module||'').trim().toUpperCase(),recordKey=String(body.recordKey||'default').trim();if(!outletId)return{ok:false,error:'outletId is required'};if(!module)return{ok:false,error:'module is required'};const payload=body.data!==undefined?body.data:{};const incomingVersion=Number(body.stateVersion||(payload&&payload._bobsMeta&&payload._bobsMeta.stateVersion)||0)||0;const now=new Date().toISOString(),values=sheet.getDataRange().getValues();let row=-1;for(let r=1;r<values.length;r++){if(String(values[r][0])===outletId&&String(values[r][1])===module&&String(values[r][2])===recordKey){row=r+1;break}}let createdAt=now;if(row===-1){sheet.appendRow([outletId,module,recordKey,createdAt,now,'ACTIVE',JSON.stringify(payload)])}else{createdAt=values[row-1][3]||now;let existingVersion=0;try{const old=JSON.parse(String(values[row-1][6]||'{}'));existingVersion=Number(old&&old._bobsMeta&&old._bobsMeta.stateVersion)||0}catch(err){}if(incomingVersion&&existingVersion&&incomingVersion<existingVersion)return{ok:true,source:'GOOGLE_SHEETS',sheet:MODULE_SHEET,outletId:outletId,module:module,recordKey:recordKey,saved:false,ignored:true,reason:'STALE_STATE_VERSION',existingVersion:existingVersion,incomingVersion:incomingVersion,createdAt:createdAt,updatedAt:values[row-1][4]};sheet.getRange(row,1,1,7).setValues([[outletId,module,recordKey,createdAt,now,'ACTIVE',JSON.stringify(payload)]])}return{ok:true,source:'GOOGLE_SHEETS',sheet:MODULE_SHEET,outletId:outletId,module:module,recordKey:recordKey,createdAt:createdAt,updatedAt:now,saved:true,verified:true}}
function getModuleData_(body){
  const sheet=ensureSheets_().module;
  const outletId=String(body.outletId||''),module=String(body.module||'').trim().toUpperCase(),recordKey=String(body.recordKey||'default').trim();
  // Scan identity columns only. Read payload only for matching identities.
  // No persistent row cache: inserts/deletes and direct Sheet edits remain visible.
  const count=sheet.getLastRow()-1;
  const keys=count>0?sheet.getRange(2,1,count,3).getValues():[];
  for(let r=0;r<keys.length;r++)if(String(keys[r][0])===outletId&&String(keys[r][1])===module&&String(keys[r][2])===recordKey){
    const row=sheet.getRange(r+2,1,1,7).getValues()[0];
    if(String(row[0])!==outletId||String(row[1])!==module||String(row[2])!==recordKey)throw Error('Module rows changed during read. Retry Google read.');
    if(String(row[5])==='DELETED')continue;
    let data;try{data=JSON.parse(String(row[6]||'{}'));}catch(err){return {ok:false,error:'Stored module payload is invalid JSON. No verified record returned.'};}
    return {ok:true,source:'GOOGLE_SHEETS',sheet:MODULE_SHEET,found:true,outletId:outletId,module:module,recordKey:recordKey,createdAt:row[3],updatedAt:row[4],status:row[5],data:data};
  }
  return {ok:true,source:'GOOGLE_SHEETS',sheet:MODULE_SHEET,found:false,outletId:outletId,module:module,recordKey:recordKey,data:null};
}
function listModuleData_(body){const sheets=ensureSheets_(),sheet=sheets.module,outletId=String(body.outletId||''),module=String(body.module||'').trim().toUpperCase(),values=sheet.getDataRange().getValues(),records=[];for(let r=1;r<values.length;r++){if(String(values[r][0])===outletId&&String(values[r][1])===module&&String(values[r][5])!=='DELETED'){let data={};try{data=JSON.parse(String(values[r][6]||'{}'))}catch(err){data={}}records.push({outletId:outletId,module:module,recordKey:String(values[r][2]),createdAt:values[r][3],updatedAt:values[r][4],status:values[r][5],data:data})}}return{ok:true,source:'GOOGLE_SHEETS',sheet:MODULE_SHEET,outletId:outletId,module:module,count:records.length,records:records}}
function deleteModuleData_(body){const sheets=ensureSheets_(),sheet=sheets.module,outletId=String(body.outletId||''),module=String(body.module||'').trim().toUpperCase(),recordKey=String(body.recordKey||'default').trim(),values=sheet.getDataRange().getValues();for(let r=1;r<values.length;r++){if(String(values[r][0])===outletId&&String(values[r][1])===module&&String(values[r][2])===recordKey){sheet.getRange(r+1,5).setValue(new Date().toISOString());sheet.getRange(r+1,6).setValue('DELETED');return{ok:true,source:'GOOGLE_SHEETS',outletId:outletId,module:module,recordKey:recordKey,deleted:true}}}return{ok:false,error:'Module record not found'}}
